
# FIXME: Tiltfile deploys helm chart as template. There is no way to track existing secrets on the cluster.
# This flag was introduced to avoid secrets update (mutation) on every file change within chart directory.
# For OpenCRVS developers there is no need to deploy dependencies helm chart as template.
chart_dev_mode: true

mongodb:
  enabled: true
  version: 4.4

minio:
  enabled: true
  use_default_credentials: true

influxdb:
  enabled: true

hearth:
  enabled: true

redis:
  enabled: true
  auth_mode: disabled
  # List of placeholders for OpenCRVS "users":
  auth_users:
    - GATEWAY
    - WORKFLOW
    - AUTH
    - WEBHOOKS

elasticsearch:
  enabled: true
  use_default_credentials: true

hostname: farajaland.dev

ingress:
  ssl_enabled: true