
mongodb:
  version: 4.4

minio: {}

influxdb: {}

hearth: {}

redis: {}

elasticsearch: {}

hostname: farajaland.dev

cert_manager:
  enabled: false
  # Check doc at: https://cert-manager.io/docs/configuration/issuers/
  cluster_issuer: "<put issuer here>"