storage_type: host_path

ingress:
  tls_resolver: letsencrypt

minio:
  use_default_credentials: false
  host_data_path: /data2/minio

elasticsearch:
  use_default_credentials: false
  host_data_path: /data2/elasticsearch
  host_backup_path: /data2/backups/elasticsearch

mongodb:
  use_default_credentials: false
  host_data_path: /data2/mongo

postgres:
  use_default_credentials: false
  host_data_path: /data2/postgres

monitoring:
  enabled: false
