# Add extra SANs to kube-apiserver certs
# FIXME: Logic here doesn't store 
- name: Dump kubeadm cluster config from configmap
  command: >
    kubectl -n kube-system get configmap kubeadm-config -o jsonpath='{.data.ClusterConfiguration}'
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: clusterconfig_raw

- name: Parse kubeadm-config as YAML
  set_fact:
    kubeadm_config_parsed: "{{ clusterconfig_raw.stdout | from_yaml }}"

# -- Get current SANs from the parsed config --
- name: Extract current SANs from config
  set_fact:
    current_sans: "{{ kubeadm_config_parsed.apiServer.certSANs | default([]) }}"

# -- Build merged list of SANs --
- name: Build new list of SANs
  set_fact:
    merged_sans: "{{ (current_sans + kube_api_sans) | unique }}"

- name: Decide if a SAN update is needed
  set_fact:
    sans_update_needed: "{{ (current_sans | sort) != (merged_sans | sort) }}"


- name: Merge updated SANs into kubeadm-config
  when: sans_update_needed
  set_fact:
    new_config: "{{ kubeadm_config_parsed | combine({'apiServer': kubeadm_config_parsed.apiServer | combine({'certSANs': merged_sans})}) }}"

- name: Write updated kubeadm-config with new SANs
  when: sans_update_needed
  copy:
    dest: /root/kubeadm-config.yaml
    content: "{{ new_config | to_nice_yaml }}"

- name: Backup existing apiserver cert and key
  when: sans_update_needed
  shell: |
    mv "/etc/kubernetes/pki/apiserver.{{ item }}" "/etc/kubernetes/pki/apiserver.{{ item }}.bak"
  loop:
    - crt
    - key
- name: Generate new apiserver certificate with updated SANs
  when: sans_update_needed
  command: kubeadm init phase certs apiserver --config /root/kubeadm-config.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Delete kube-apiserver pods to restart with new certs
  when: sans_update_needed
  command: kubectl -n kube-system delete pod -l component=kube-apiserver --timeout=30s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Check api-server status
  shell: |
    kubectl wait --for=condition=ready pod -l component=kube-apiserver -n kube-system --timeout=30s
  register: kubectl_result
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  retries: 5
  delay: 10

- name: Show result of restart
  debug:
    var: kubectl_result.stdout

- name: Copy admin.conf to provision user's kube config
  when: sans_update_needed
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/provision/.kube/config
    owner: provision
    group: provision
    mode: '0600'
    remote_src: yes
    force: yes

- name: Create scripts directory for {{ ansible_user }}
  file:
    # FIXME: Should we use /opt/opencrvs instead?
    path: /home/{{ ansible_user }}/scripts
    state: directory
    owner: "{{ ansible_user }}"
    group: application
    mode: '0775'

- name: Create script for kubernetes user management
  copy:
    src: ./files/add-k8s-user.sh
    dest: "/home/{{ ansible_user }}/scripts/add-k8s-user.sh"
    owner: "{{ ansible_user }}"
    group: 'application'
    mode: '0755'