
{{- if not .Values.elasticsearch.use_default_credentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-opencrvs-users
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ELASTIC_PASSWORD: {{ randAlphaNum 32 | b64enc }}
{{- end }}