
{{- if not .Values.elasticsearch.use_default_credentials }}
{{/* Prevent secret mutation between helm upgrades */}}
{{- $secret_name := "elasticsearch-opencrvs-users" }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secret_name }}
{{- if not $secret }}
{{- $secrets := dict }}
{{- $default_password := randAlphaNum 32 }}
{{- if $.Values.chart_dev_mode }}
{{- $default_password = "elasticpassword" }}
{{- end }}
{{- $_ := set $secrets "ELASTIC_PASSWORD" $default_password }}

{{- range $user_props := .Values.elasticsearch.auth_users }}
  {{- $user_key_val := split ":" $user_props }}
  {{- $user_key := $user_key_val._0 }}
  {{- $user_name := $user_key_val._1 | default $user_key }}

  {{- $username := randAlphaNum 16 }}
  {{- $password := randAlphaNum 32 }}
  {{- if $.Values.chart_dev_mode }}
    {{- $username = $user_name | lower }}
    {{- $password = $user_name | lower }}
  {{- end }}
  {{- $_ := set $secrets (printf "%s_ELASTIC_USERNAME" $user_key) $username }}
  {{- $_ := set $secrets (printf "%s_ELASTIC_PASSWORD" $user_key) $password }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := $secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}


{{- end }}
{{- end }}