{{ if .Values.elasticsearch.enabled }}
{{- $storageType := default .Values.storage_type .Values.elasticsearch.storage_type | default "pvc" }}
{{- if eq $storageType "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "5Gi" .Values.elasticsearch.data_storage_size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: elasticsearch-backup
  name: elasticsearch-backup
spec:
  {{- if .Values.elasticsearch.backup_storage_class }}
  storageClassName: {{ .Values.elasticsearch.backup_storage_class }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "1Gi" .Values.elasticsearch.backup_storage_size }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  clusterIP: None
  ports:
    - name: '9200'
      port: 9200
      targetPort: 9200
    - name: '9300'
      port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch

{{- if .Values.backup.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-backup-jobs
data:
  root: |
    {{ .Values.elasticsearch.backup_schedule | default .Values.backup.schedule }} /scripts/backup.sh >> /proc/1/fd/1 2>&1
{{- end }}

{{- if .Values.restore.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-restore-jobs
data:
  root: |
    {{ .Values.elasticsearch.restore_schedule | default .Values.restore.schedule }} /scripts/restore.sh >> /proc/1/fd/1 2>&1
{{- end }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: 'elasticsearch'
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
    {{- if .Values.priority_class.enabled }}
      priorityClassName: datastore-high-priority
    {{- end }}
    {{- $node_selector := default .Values.node_selector .Values.elasticsearch.node_selector }}
    {{- if $node_selector }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
            {{- range $k, $v := $node_selector }}
              - key: {{ $k }}
                operator: In
                values:
                - {{ $v }}
            {{- end }}
      {{- end }}
      initContainers:
        # Change ownership to elasticsearch user and group
        - name: volume-permission-fix
          image: busybox
          command:
            - chown
            - -R
            - "1000:0"
            - /usr/share/elasticsearch/data
            - /data/backups/elasticsearch
          volumeMounts:
            - name: elasticsearch
              mountPath: /usr/share/elasticsearch/data
            - mountPath: /data/backups/elasticsearch
              name: elasticsearch-backup
      containers:
        - env:
            # FIXME: Make fields configurable
            - name: ES_JAVA_OPTS
              value: -Xms2048m -Xmx8192m
            - name: cluster.routing.allocation.disk.threshold_enabled
              value: 'false'
            - name: discovery.type
              value: single-node
            - name: path.repo
              value: /data/backups/elasticsearch
          {{- if not .Values.elasticsearch.use_default_credentials }}
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elasticsearch.admin_user_secret_name }}
                  key: ELASTIC_PASSWORD
            - name: xpack.security.enabled
              value: 'true'
          {{- else }}
            - name: xpack.security.enabled
              value: 'false'
          {{- end }}
          {{- if or .Values.elasticsearch.secrets .Values.elasticsearch.env .Values.env }}
          {{- include "render-env-vars" (dict "service_name" "elasticsearch" "Values" .Values) }}
          {{- end }}
          image: docker.elastic.co/elasticsearch/elasticsearch:8.16.4
          name: elasticsearch
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "8Gi"
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch
            - mountPath: /data/backups/elasticsearch
              name: elasticsearch-backup
      {{- if .Values.backup.enabled }}
        - name: backup
          command: ["crond", "-f", "-L", "/var/log/cron.log"]
          image: "bash"
          env:
          {{- if not .Values.elasticsearch.use_default_credentials }}
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elasticsearch.admin_user_secret_name }}
                  key: ELASTIC_PASSWORD
          {{- end }}
            - name: ENCRYPT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.backup_encryption_secret }}
                  key: backup_encryption_key
            - name: BACKUP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.backup_server_secret }}
                  key: user
            - name: BACKUP_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.backup_server_secret }}
                  key: host
            - name: BACKUP_REMOTE_DIR
              value: "{{ .Values.elasticsearch.backup_server_dir | default .Values.backup.backup_server_dir }}"
          volumeMounts:
            - name: backup-ssh-key
              mountPath: /ssh
              readOnly: true
            - mountPath: /data/backups/elasticsearch
              name: elasticsearch-backup
            - mountPath: /scripts
              name: elasticsearch-scripts
            - name: backup-crontab
              mountPath: /etc/crontabs
      {{- end }}
      {{- if .Values.restore.enabled }}
        - name: restore
          command: ["crond", "-f", "-L", "/var/log/cron.log"]
          # command: ["/scripts/restore.sh"]
          image: "bash"
          env:
          {{- if not .Values.elasticsearch.use_default_credentials }}
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elasticsearch.admin_user_secret_name }}
                  key: ELASTIC_PASSWORD
          {{- end }}
            - name: ENCRYPT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.restore.backup_encryption_secret }}
                  key: backup_encryption_key
            - name: BACKUP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.restore.backup_server_secret }}
                  key: user
            - name: BACKUP_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.restore.backup_server_secret }}
                  key: host
            - name: BACKUP_REMOTE_DIR
              value: "{{ .Values.elasticsearch.restore_server_dir | default .Values.restore.backup_server_dir }}"
          volumeMounts:
            - name: restore-ssh-key
              mountPath: /ssh
              readOnly: true
            - mountPath: /data/backups/elasticsearch
              name: elasticsearch-backup
            - mountPath: /scripts
              name: elasticsearch-scripts
            - name: restore-crontab
              mountPath: /etc/crontabs
      {{- end }}
      restartPolicy: Always
      volumes:
        - name: elasticsearch
      {{- if eq $storageType "pvc" }}
          persistentVolumeClaim:
            claimName: elasticsearch
      {{- else if eq $storageType "host_path" }}
          hostPath:
            path: {{ .Values.elasticsearch.host_data_path | default "/data/elasticsearch" }}
            type: DirectoryOrCreate
      {{- end }}
        - name: elasticsearch-backup
      {{- if eq $storageType "pvc" }}
          persistentVolumeClaim:
            claimName: elasticsearch-backup
      {{- else if eq $storageType "host_path" }}
          hostPath:
            path: {{ .Values.elasticsearch.host_backup_path | default "/data/backups/elasticsearch" }}
            type: DirectoryOrCreate
      {{- end }}
      {{- if or .Values.backup.enabled .Values.restore.enabled }}
        - name: elasticsearch-scripts
          configMap:
            name: elasticsearch-scripts
            defaultMode: 0755
      {{- end }}
      {{- if or .Values.backup.enabled }}
        - name: backup-ssh-key
          secret:
            secretName: {{ .Values.backup.backup_server_secret }}
            defaultMode: 0400
            items:
              - key: ssh_key
                path: ssh_key
        - name: backup-crontab
          configMap:
            name: elasticsearch-backup-jobs
      {{- end }}
      {{- if or .Values.restore.enabled }}
        - name: restore-ssh-key
          secret:
            secretName: {{ .Values.backup.backup_server_secret }}
            defaultMode: 0400
            items:
              - key: ssh_key
                path: ssh_key
        - name: restore-crontab
          configMap:
            name: elasticsearch-restore-jobs
      {{- end }}
{{- end }}