{{- if .Values.monitoring.enabled }}
apiVersion: v1
data:
{{- range $path, $file := .Files.Glob "files/kibana/*" }}
    {{ base $path }}: |
{{ toString $file | indent 8 }}
{{- end }}
kind: ConfigMap
metadata:
  labels:
    app: kibana
  name: kibana-on-update-script
{{- end }}
