{{- if .Values.monitoring.enabled }}
{{- $secret_name := "kibana-encryption-secret" }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secret_name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
stringData:
  KIBANA_ENCRYPTION_KEY: {{ .Values.encryptionKey | default (randAlphaNum 32) }}
{{- end }}