{{ if .Values.minio.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minio
  name: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-route
spec:
  entryPoints:
  {{- if .Values.ingress.ssl_enabled }}
    - websecure
  {{- else }}
    - web
  {{- end }}
  routes:
  - match: 'Host(`minio.{{ .Values.hostname }}`)'
    kind: Rule
    services:
    - name: minio
      namespace: {{ .Release.Namespace }}
      port: 3535
  - match: 'Host(`minio-console.{{ .Values.hostname }}`)'
    kind: Rule
    services:
    - name: minio
      namespace: {{ .Release.Namespace }}
      port: 3536
  {{- if .Values.ingress.tls_resolver }}
  tls:
    certResolver: {{ .Values.ingress.tls_resolver }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
spec:
  clusterIP: None
  ports:
    - name: '3535'
      port: 3535
      targetPort: 3535
    - name: '3536'
      port: 3536
      targetPort: 3536
  selector:
    app: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: minio
  name: minio
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
    {{- if .Values.node_label_selector }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
            {{- range $k, $v := .Values.node_label_selector }}
              - key: {{ $k }}
                operator: In
                values:
                - {{ $v }}
            {{- end }}
      {{- end }}
      containers:
        - args:
            - server
            - --address
            - :3535
            - --console-address
            - :3536
            - /data
          # image: quay.io/minio/minio:RELEASE.2023-09-16T01-01-47Z.fips
          image: minio/minio:RELEASE.2023-08-16T20-17-30Z.hotfix.a51234923
          # image: minio/minio:RELEASE.2025-03-12T18-04-18Z
          name: minio
          env:
            - name: MINIO_BROWSER_REDIRECT_URL
              value: {{ include "render-external-url" (dict "service_name" "minio-console" "Values" .Values) }}
            - name: MINIO_DOMAIN
              value: {{ include "render-external-url" (dict "service_name" "minio" "Values" .Values) }}
            - name: MINIO_API_CORS_ALLOW_ORIGIN
              value: '*'
          {{- if not .Values.minio.use_default_credentials }}
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-opencrvs-users
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-opencrvs-users
                  key: MINIO_ROOT_PASSWORD
          {{- end }}
          {{- include "render-env-vars" (dict "service_name" "minio" "Values" .Values) }}
          ports:
            - containerPort: 3535
              protocol: TCP
            - containerPort: 3536
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: minio
      restartPolicy: Always
      volumes:
        - name: minio
          persistentVolumeClaim:
            claimName: minio
{{- end }}