
{{- if not .Values.minio.use_default_credentials }}

{{- $username := randAlphaNum 16 }}
{{- $password := randAlphaNum 32 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-opencrvs-users
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ $username | b64enc }}
  MINIO_ROOT_PASSWORD: {{ $password | b64enc }}
  MINIO_ROOT_USER: {{ $username | b64enc }}
  MINIO_SECRET_KEY: {{ $password | b64enc }}

{{- end }}