{{- if not .Values.mongodb.use_default_credentials }}
apiVersion: v1
data:
  on-deploy.sh: |
    {{- .Files.Get "files/mongodb-create-users.sh" | indent 8 }}
kind: ConfigMap
metadata:
  labels:
    app: mongo
  name: mongo-on-update-script
{{- end }}
