{{ if .Values.postgres.enabled }}
{{- $storageType := default .Values.storage_type .Values.postgres.storage_type | default "pvc" }}
{{- if eq $storageType "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "1Gi" .Values.postgres.data_storage_size }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
    {{- if .Values.priority_class.enabled }}
      priorityClassName: {{ .Values.priority_class.name }}
    {{- end }}
    {{- $node_selector := default .Values.node_selector .Values.postgres.node_selector }}
    {{- if $node_selector }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
            {{- range $k, $v := $node_selector }}
              - key: {{ $k }}
                operator: In
                values:
                - {{ $v }}
            {{- end }}
      {{- end }}
      containers: 
        - image: docker.io/chumaky/postgres_mongo_fdw:17.6_fdw5.5.2
          name: postgres
          env:
          {{- if .Values.postgres.use_default_credentials }}
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          {{- else }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.admin_user_secret_name }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.admin_user_secret_name }}
                  key: POSTGRES_PASSWORD
          {{- end }}
          {{- include "render-env-vars" (dict "service_name" "postgres" "Values" .Values) }}
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
      restartPolicy: Always
      volumes:
        - name: postgres
      {{- if eq $storageType "pvc" }}
          persistentVolumeClaim:
            claimName: postgres
      {{- else if eq $storageType "host_path" }}
          hostPath:
            path: {{ .Values.postgres.host_data_path | default "/data/postgres" }}
            type: DirectoryOrCreate
      {{- end }}
{{- end }}
