{{/*
Create postgres Admin user (superuser)
*/}}
{{- if not .Values.postgres.use_default_credentials }}

{{/* Prevent secret mutation between helm upgrades */}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.postgres.admin_user_secret_name }}
{{- if not $secret }}
  {{- $admin_user := "postgres" }}
  {{- $admin_password := randAlphaNum 16 }}
  {{- if $.Values.chart_dev_mode }}
    {{- $admin_password = "password" }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.admin_user_secret_name }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  POSTGRES_USER: {{ $admin_user | b64enc }}
  POSTGRES_PASSWORD: {{ $admin_password | b64enc }}
{{- end }}
{{- end }}
