{{- if .Values.priority_class.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: datastore-high-priority
value: 1000000
globalDefault: false
description: "High priority for Datastore pods"
{{- end }}