
{{- if .Values.redis.acl.enabled }}

{{- $secrets := dict }}
{{- $_ := set $secrets "DEFAULT_REDIS_PASSWORD" (randAlphaNum 32) }}
{{- range .Values.redis.acl.users }}
  {{- $_ := set $secrets (printf "%s_REDIS_USERNAME" .) (randAlphaNum 16) }}
  {{- $_ := set $secrets (printf "%s_REDIS_PASSWORD" .) (randAlphaNum 32) }}
{{- end }}

{{- /* Build ACL file content */}}
{{- $acl := printf "user default on >%s ~* +@all\n" ($secrets.DEFAULT_REDIS_PASSWORD) }}
{{- range .Values.redis.acl.users }}
  {{- $username := index $secrets (printf "%s_REDIS_USERNAME" .) }}
  {{- $password := index $secrets (printf "%s_REDIS_PASSWORD" .) }}
  {{- $acl = printf "%suser %s on >%s ~* +@all\n" $acl $username $password }}
{{- end }}


---
apiVersion: v1
kind: Secret
metadata:
  name: redis-opencrvs-acl
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  users.acl: {{ $acl | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-opencrvs-users
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := $secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}

{{- end }}