{{ if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: bitnami/redis:latest
          name: redis
          env:
          {{- if eq .Values.redis.auth_mode "acl" }}
            - name: REDIS_ACLFILE
              value: /opt/bitnami/redis/mounted-etc/users.acl
            - name: REDIS_PASSWORD
              value: "false"
          {{- else if eq .Values.redis.auth_mode "password" }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-opencrvs-users
                  key: DEFAULT_REDIS_PASSWORD
          {{- else }}
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          {{- end }}

          {{- include "render-env-vars" (dict "service_name" "redis" "Values" .Values) }}
          ports:
            - containerPort: 6379
              protocol: TCP
          {{- if eq .Values.redis.auth_mode "acl" }}
          volumeMounts:
            - name: redis-opencrvs-acl
              mountPath: /opt/bitnami/redis/mounted-etc
              # subPath: redis-acl.conf
          {{- end }}
      restartPolicy: Always
      volumes:
        {{- if eq .Values.redis.auth_mode "acl" }}
        - name: redis-opencrvs-acl
          secret:
            secretName: redis-opencrvs-acl
        {{- end }}
{{- end }}
