{{ if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: bitnami/valkey:latest
          name: redis
          env:
          {{- if .Values.redis.acl.enabled }}
            - name: VALKEY_ACLFILE
              value: /opt/bitnami/valkey/mounted-etc/users.acl
            - name: VALKEY_PASSWORD
              value: "false"
          {{- end }}
          {{- include "render-env-vars" (dict "service_name" "redis" "Values" .Values) }}
          ports:
            - containerPort: 6379
              protocol: TCP
          {{- if .Values.redis.acl.enabled }}
          volumeMounts:
            - name: redis-opencrvs-acl
              mountPath: /opt/bitnami/valkey/mounted-etc
              # subPath: redis-acl.conf
          {{- end }}
      restartPolicy: Always
      volumes:
        {{- if .Values.redis.acl.enabled }}
        - name: redis-opencrvs-acl
          secret:
            secretName: redis-opencrvs-acl
        {{- end }}
{{- end }}
