chart_dev_mode: true
hostname: aws.opencrvs.dev

redis:
  # TODO: auth mode values doesn't match with opencrvs-services chart
  auth_mode: acl

minio:
  use_default_credentials: false

elasticsearch:
  use_default_credentials: false

mongodb:
  use_default_credentials: false

# TODO: revise naming
# probably set better name like node_selector, etc.
affinity:
 role: data1