all:
  vars:
    # Add IP addresses or domain names for communication with your cluster from your laptop
    # NOTE: First item in this list will be added as main endpoint to your ~/.kube/config
    # - If you are behind VPN, use private IP address
    # - If your server is exposed (not recommeded), use public IP address
    # - If you would like to run kubectl commands from the remote server, leave this field empty
    kube_api_sans: []
    # Keep default
    ansible_user: provision
    # For development/qa/testing/staging keep true
    # For production keep false
    single_node: true
     # Add as many users as you wish
    users: []
  children:
    master:
      hosts:
        # IMPORTANT: Update with your real host name
        test-k8s-master:
          ansible_host: localhost
          ansible_connection: local
