##################################################################################
# Use this file to customize helm chart behavior
# Please make sure your custom changes doesn't conflict with values.yaml
##################################################################################
gateway:
  env:
    DISABLE_RATE_LIMIT: "true"

network_policy:
  ingress_mode: deny
  egress_mode: deny
  allowed_namespaces:
    - opencrvs-deps-perftest

elasticsearch:
  reindex_enabled: false