apiVersion: v1
kind: Service
metadata:
  labels:
    app: workflow
  name: workflow
spec:
  ports:
    - port: 5050
      targetPort: 5050
  selector:
    app: workflow
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workflow
  name: workflow
spec:
  replicas: {{ .Values.workflow.replicas }}
  selector:
    matchLabels:
      app: workflow
  template:
    metadata:
      labels:
        app: workflow
    spec:
      containers:
        - name: workflow
          image: "ghcr.io/opencrvs/ocrvs-workflow:{{ .Values.image.tag }}"
          env:
            - name: APPLICATION_CONFIG_URL
              value: http://config.opencrvs-services-dev.svc.cluster.local:2021 # FIXME: harcoded/
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: COUNTRY
              value: bgd
            - name: COUNTRY_CONFIG_URL
              value: http://countryconfig.opencrvs-services-dev.svc.cluster.local:3040 # FIXME: harcoded
            - name: DOCUMENTS_URL
              value: http://documents.opencrvs-services-dev.svc.cluster.local:9050 # FIXME: harcoded
            - name: FHIR_URL
              value: http://hearth-1.hearth.opencrvs-deps-dev.svc.cluster.local:3447/fhir # FIXME: harcoded
            - name: METRICS_URL
              value: http://metrics.opencrvs-services-dev.svc.cluster.local:1050 # FIXME: harcoded
            - name: NODE_ENV
              value: development
            - name: NOTIFICATION_SERVICE_URL
              value: http://notification.opencrvs-services-dev.svc.cluster.local:2020/
            - name: SEARCH_URL
              value: http://search.opencrvs-services-dev.svc.cluster.local:9090/ # FIXME: harcoded
            - name: USER_MANAGEMENT_URL
              value: http://user-mgnt.opencrvs-services-dev.svc.cluster.local:3030/ # FIXME: hardcoded
            - name: WEBHOOKS_URL
              value: http://webhooks.opencrvs-services-dev.svc.cluster.local:2525/
          ports:
            - containerPort: 5050
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: public-key
          name: public-key