storage_type: host_path

ingress:
  tls_resolver: letsencrypt

minio:
  use_default_credentials: false

elasticsearch:
  use_default_credentials: false

mongodb:
  use_default_credentials: false

postgres:
  use_default_credentials: false

monitoring:
  enabled: true

redis:
  auth_mode: acl

elastalert:
  env:
    HTTP_POST2_ALERT_URL: http://countryconfig.opencrvs-dev.svc.cluster.local:3040/email

backup:
  enabled: true
  backup_server_dir: /home/backup/dev