elasticsearch_host: elasticsearch.opencrvs-deps-demo.svc.cluster.local:9200
influxdb:
  host: influxdb-0.influxdb.opencrvs-deps-demo.svc.cluster.local
fhir_url: http://hearth.opencrvs-deps-demo.svc.cluster.local:3447/fhir

minio:
  host: minio-0.minio.opencrvs-deps-demo.svc.cluster.local
redis_host: redis-0.redis.opencrvs-deps-demo.svc.cluster.local
mongodb_host: mongodb-0.mongodb.opencrvs-deps-demo.svc.cluster.local

resources:
  memoryRequest: "512Mi"
  cpuRequest: "300m"
  memoryLimit: "1Gi"
  cpuLimit: "2"

hostname: aws.opencrvs.dev

image:
  tag: develop

countryconfig:
  image:
    # Replace countryconfig with farajaland to test data
    name: opencrvs/ocrvs-farajaland
    # name: opencrvs/ocrvs-countryconfig
    tag: develop

documents:
  secrets:
    minio-opencrvs-users:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY

auth:
  secrets:
    redis-opencrvs-users:
      - AUTH_REDIS_PASSWORD:REDIS_PASSWORD
      - AUTH_REDIS_USERNAME:REDIS_USERNAME
gateway:
  secrets:
    redis-opencrvs-users:
      - GATEWAY_REDIS_PASSWORD:REDIS_PASSWORD
      - GATEWAY_REDIS_USERNAME:REDIS_USERNAME
  # # Uncomment this section to add authentication for MinIO:
  #   minio-opencrvs-users:
  #   # TODO: Check if it is needed
  #   - MINIO_BUCKET

migration:
  secrets:
# Uncomment this section to add authentication for MinIO:
    minio-opencrvs-users:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
data_cleanup:
  secrets:
    minio-opencrvs-users:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD

data_seeder:
  # Change to true to enable data seeder
  enabled: true
webhooks:
  secrets:
    redis-opencrvs-users:
      - WEBHOOKS_REDIS_PASSWORD:REDIS_PASSWORD
      - WEBHOOKS_REDIS_USERNAME:REDIS_USERNAME

workflow:
  secrets:
    redis-opencrvs-users:
      - WORKFLOW_REDIS_PASSWORD:REDIS_PASSWORD
      - WORKFLOW_REDIS_USERNAME:REDIS_USERNAME