all:
  vars:
    kube_api_sans:
      - test-k8s.opencrvs.dev
    ansible_user: provision
    single_node: true
    users:
      - name: vmudryi
        ssh_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINgMcsSBwTE0EbMDRSF1T4vJDcN/5HAjKGbi2DqV7g/Q vmudryi@opencrvs.org
        state: present
        role: admin
  children:
    master:
      hosts:
        test-k8s-master:
          ansible_host: localhost
          ansible_connection: local
