all:
  vars:
    kube_api_sans:
      - 5.78.158.131
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: provision
    single_node: false
    users:
      - name: vmudryi
        ssh_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINgMcsSBwTE0EbMDRSF1T4vJDcN/5HAjKGbi2DqV7g/Q vmudryi@opencrvs.org
        state: present
        sudoer: true
  children:
    master:
      hosts:
        test-k8s-master:
          ansible_host: 5.78.158.131
    workers:
      hosts:
        test-k8s-worker-0:
          ansible_host: 5.78.67.216
        test-k8s-worker-1:
          ansible_host: 5.78.153.188
        test-k8s-worker-2:
          ansible_host: 5.78.133.88