all:
  vars:
    # Domain/IP address for remote access to your cluster API (see ~/.kube/config)
    # - If you are behind VPN, use private IP address
    # - If your server is exposed (not recommeded), use public IP address
    # - If you would like to run kubectl commands from the remote server, leave this field empty
    # kube_api_host: ''
    kube_api_host: 37.27.199.74
    # Default ansible provision user, keep as is
    ansible_user: provision

    # single_node:
    # For development/qa/testing/staging keep true
    # For production keep false
    # Defaults production configuration:
    # - master node
    # - 2 worker nodes
    single_node: true

    # users: Add as many users as you wish
    # Configuration example
    # - name: <login>
    #   ssh_keys:
    #     - <public ssh key 1>
    #     - <public ssh key 2>
    #   state: present
    #   role: admin
    # Allowed roles:
    # - operator, read only access to OS, full access to kubernetes cluster
    # - admin, full access
    # Allowed states:
    # - present, user is allowed to login
    # - absent, account is disabled
    users: 
      - name: euan
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDECqHO65UpyrrO8uueD06RxGaVVq22f152Rf8qVQQAAIGAMu6gCs7ztlZ8a3yQgSEIjM/Jl1/RqIVs6CziTEef74nLFTZ5Ufz3CLRVgdebBeSBEmhTfTUV0HLkSyNzwKFpuzJxucGd72ulPvEp6eHvyJAPJz37YcU8cjaL1v05T6s2ee99li35GlDDtCzfjVV4ZPAg5JdfWuTj41RAVC0LQhk2/NB4qEu37UxGGjhRFSjBEsS5LxI9QfvgrsHpl/VOn+soH7ZkK7kS6qRgNP/uYsXRWXhHaamcl5OX68gJWTbrW6c7PCqlbCWGnsHJswCmqPIthwXXMfC7ULDNLSKG6mslAt5Dyc8/MCr3vTW7pDyr2d0FvvY86SMQUggxv3qF7TZewqfX1bhK0fMLarIxVMQ1RFo//wN9QGA+2we8rxd2Y1Kr1DBuJyuwXPfv+Exo8yNYQ+x/AYH5k6UVcSYuaB8eYmplG2KQCxt8RBFtoChrwOKNRWLqXdKyfpdp5XmnnWxPvR95gf3h3yLocVYkF0i0uvKKJ0vt8J0Ezfkdfow0B1kUg5bPXKJROX7PwbaCPdYcxyDaO6wwOigRnSmoFvkH1pLb4j1RQAXcX531CHgfN6Izi/h0mpMS4bnyIUcv2GQr+h4z4TxcCtj7qpH2y6yw7XG12jVh7TfeesXG2Q== euanmillar77@gmail.com
        state: present
        role: admin
      - name: vadym
        ssh_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINgMcsSBwTE0EbMDRSF1T4vJDcN/5HAjKGbi2DqV7g/Q vmudryi@opencrvs.org
        state: present
        role: admin

  children:
    master:
      hosts:
        # Replace master with value returned by command: hostname
        master:
          # Keep values (ansible_host, ansible_connection) as is
          # Ansible is executed on master node
          ansible_host: localhost
          ansible_connection: local
