minio:
  env:
    MINIO_BROWSER_REDIRECT_URL: http://minio.opencrvs.localhost
    MINIO_DOMAIN: opencrvs.localhost
    MINIO_API_CORS_ALLOW_ORIGIN: '*'

hostname: opencrvs.localhost

ingress:
  ssl_enabled: false