hostname: opencrvs.localhost

ingress:
  ssl_enabled: false

redis:
  auth_mode: acl

minio:
  # TODO: Revisit naming convention
  # use_default_credentials could be applied to redis and other services as well
  use_default_credentials: false

elasticsearch:
  use_default_credentials: false
