# Overwriting https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
namespaceOverride: "traefik"
logs:
  general:
    # "TRACE", "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
    level: "WARN"
    format: "common" # FIXME: json in remote
  access:
    # -- To enable access logs
    enabled: true
ingressRoute:
  dashboard:
    enabled: true
    entryPoints: ["web", "websecure"]
    matchRule: Host(`traefik.k8s.opencrvs.dev`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
# Be explicit that we only use CRDs, not ingress/gw support
providers: 
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: false
service:
  enabled: true
  single: false
  type: LoadBalancer
