apiVersion: v1
kind: Service
metadata:
  labels:
    app: countryconfig
  name: countryconfig
spec:
  ports:
    - port: 3040
      targetPort: 3040
  selector:
    app: countryconfig
  type: LoadBalancer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: countryconfig-route
spec:
  entryPoints:
    - websecure
  routes:
  - match: 'Host(`countryconfig.{{ .Values.hostname }}`) && !Path(`/email`) && !Path(`/notification`) && !Path(`/dashboards/queries.json`)'
    kind: Rule
    services:
    - name: countryconfig
      namespace: opencrvs-services-dev
      port: 3040
    middlewares:
      - name: sts-and-basic-response-headers
      - name: enable-compression
  - match: 'Host(`countryconfig.{{ .Values.hostname }}`) && Path(`/email`)'
    kind: Rule
    services:
    - name: countryconfig
      namespace: opencrvs-services-dev
      port: 3040
    middlewares:
      - name: block-internal-routes
  - match: 'Host(`countryconfig.{{ .Values.hostname }}`) && Path(`/notification`)'
    kind: Rule
    services:
    - name: countryconfig
      namespace: opencrvs-services-dev
      port: 3040
    middlewares:
      - name: block-internal-routes
  - match: 'Host(`countryconfig.{{ .Values.hostname }}`) && Path(`/dashboards/queries.json`)'
    kind: Rule
    services:
    - name: countryconfig
      namespace: opencrvs-services-dev
      port: 3040
    middlewares:
      - name: block-internal-routes
  # tls:
  #   certResolver: myresolver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: countryconfig
  name: countryconfig
spec:
  replicas: {{ .Values.countryconfig.replicas }}
  selector:
    matchLabels:
      app: countryconfig
  template:
    metadata:
      labels:
        app: countryconfig
    spec:
      containers:
        - name: countryconfig
          image: "{{ .Values.countryconfig.image.name }}:{{ .Values.countryconfig.image.tag }}"
          env:
            - name: FHIR_URL
              value: {{ .Values.fhir_url | quote }}
            - name: CLIENT_APP_URL
              value: "https://register.{{ .Values.hostname }}"
            - name: LOGIN_URL
              value: "https://login.{{ .Values.hostname }}"
            # TODO: Check if this value is needed here?
            - name: COUNTRY_CONFIG_URL
              value: "https://countryconfig.{{ .Values.hostname }}"
            - name: DOMAIN
              value: {{ .Values.hostname | quote }}
          {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
          {{- end }}
          {{- range $k, $v := .Values.countryconfig.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
          {{- end }}
          ports:
            - containerPort: 3040
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: public-key
          name: public-key