apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    # FIXME: This is likely not gonna work as expected and is naive implementation
    # see also https://github.com/opencrvs/opencrvs-core/issues/7451
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1" # Execute migration job before other jobs
  labels:
    app: migration
  name: data-migration
spec:
  template:
    metadata:
      labels:
        app: migration
    spec:
      containers:
        - name: migration
          image: "ghcr.io/opencrvs/ocrvs-migration:{{ .Values.image.tag }}"
          env:
          {{- if eq .Values.elasticsearch.auth_mode "disabled" }}
            - name: ES_HOST
              value: "{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}"
          {{- else if or (eq .Values.elasticsearch.auth_mode "auto") (eq .Values.elasticsearch.auth_mode "use_secret") }}
            - name: ES_HOST
              valueFrom:
                secretKeyRef:
                  key: SEARCH_ELASTIC_HOST
                  name: {{ .Values.elasticsearch.urls_secret }}
          {{- end }}
            - name: SEARCH_URL
              value: http://search.{{ .Release.Namespace }}.svc.cluster.local:9090/
            - name: EVENTS_URL
              value: http://events.{{ .Release.Namespace }}.svc.cluster.local:5555/
            - name: AUTH_URL
              value: http://auth.{{ .Release.Namespace }}.svc.cluster.local:4040/
            - name: INFLUX_DB
              value: {{ .Values.influxdb.db | quote }}
            - name: INFLUX_HOST
              value: {{ .Values.influxdb.host | quote }}
            - name: INFLUX_PORT
              value: {{ .Values.influxdb.port | quote }}
            - name: MINIO_HOST
              value: {{ .Values.minio.host | quote }}
          {{- if eq .Values.mongodb.auth_mode "disabled" }}
            - name: APPLICATION_CONFIG_MONGO_URL
              value: mongodb://{{ .Values.mongodb.host }}/application-config
            - name: USER_MGNT_MONGO_URL
              value: mongodb://{{ .Values.mongodb.host }}/user-mgnt
            - name: PERFORMANCE_MONGO_URL
              value: mongodb://{{ .Values.mongodb.host }}/performance
            - name: HEARTH_MONGO_URL
              value: mongodb://{{ .Values.mongodb.host }}/hearth-dev
            - name: OPENHIM_MONGO_URL
              value: mongodb://{{ .Values.mongodb.host }}/openhim-dev
            - name: DASHBOARD_MONGO_URL
              value: mongodb://{{ .Values.mongodb.host }}/performance
            - name: EVENTS_MONGO_URL
              value: mongodb://{{ .Values.mongodb.host }}/events
          {{- else if or (eq .Values.mongodb.auth_mode "auto")  (eq .Values.mongodb.auth_mode "use_secret") }}
            - name: APPLICATION_CONFIG_MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: CONFIG_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
            - name: DASHBOARD_MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: METRICS_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
            - name: USER_MGNT_MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: USER_MGNT_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
            - name: PERFORMANCE_MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: PERFORMANCE_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
            - name: HEARTH_MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: HEARTH_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
            - name: OPENHIM_MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: OPENHIM_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
            - name: EVENTS_MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: EVENTS_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
          {{- end }}
          {{- if not (eq .Values.postgres.auth_mode "managed") }}
            - name: EVENTS_POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  key: events_migrator_db_url
                  name: {{ .Values.postgres.urls_secret }}
          {{- end }}
          {{- if or (eq .Values.minio.auth_mode "auto") (eq .Values.minio.auth_mode "use_secret") }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: MINIO_ACCESS_KEY
                  name: {{ .Values.minio.users_secret }}
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: MINIO_SECRET_KEY
                  name: {{ .Values.minio.users_secret }}
          {{- end }}
            - name: WAIT_HOSTS
              value: "{{ .Values.postgres.host }}:5432,{{ .Values.mongodb.host }}:27017,{{ .Values.influxdb.host }}:{{ .Values.influxdb.port }},{{ .Values.minio.host }}:{{ .Values.minio.port }},{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}"
          {{- include "render-env-vars" (dict "service_name" "migration" "Values" .Values) }}
      restartPolicy: "OnFailure"