{{- if .Values.data_cleanup.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: data-cleanup
  name: data-cleanup
spec:
  template:
    metadata:
      labels:
        app: data-cleanup
    spec:
      containers:
        - name: cleanup-mongo
          image: "mongo:4.4"
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Running mongo cleanup script..."
              DATABASES=("hearth-dev" "openhim-dev" "user-mgnt" "application-config" "metrics" "performance")
              for DB in "${DATABASES[@]}"; do
                echo "Dropping database: $DB"
                mongo --host $MONGO_HOST --eval "db.getSiblingDB('$DB').dropDatabase()"
              done
              echo "Cleanup complete!"
          env:
            - name: MONGO_HOST
              value: {{ .Values.mongodb_host }}
          {{- include "render-env-vars" (dict "service_name" "data_cleanup" "Values" .Values) }}
        - name: cleanup-minio
          image: "minio/mc"
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Running mongo cleanup script..."
              mc alias set myminio http://$MINIO_HOST:$MINIO_PORT ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin}
              mc rm --recursive --force myminio/ocrvs
              mc rb myminio/ocrvs
              mc mb myminio/ocrvs
              echo "Cleanup complete!"
          env:
            - name: MINIO_HOST
              value: {{ .Values.minio.host }}
            - name: MINIO_PORT
              value: {{ .Values.minio.port | quote }}
          {{- include "render-env-vars" (dict "service_name" "data_cleanup" "Values" .Values) }}
        - name: cleanup-elasticsearch
          image: "appropriate/curl"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Running elasticsearch cleanup script..."
              indices=$(curl -sS -XGET http://$ELASTICSEARCH_HOST/_cat/indices?h=index)
              echo "--------------------------"
              echo "🧹 cleanup for indices from $ELASTICSEARCH_HOST: $indices"
              echo "--------------------------"
              for index in $indices; do
                echo "Delete index $index..."
                curl -sS -XDELETE http://$ELASTICSEARCH_HOST/$index
              done
          env:
            - name: ELASTICSEARCH_HOST
              value: {{ .Values.elasticsearch_host }}
          {{- include "render-env-vars" (dict "service_name" "data_cleanup" "Values" .Values) }}
        - name: cleanup-influxdb
          image: "appropriate/curl"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Running elasticsearch cleanup script..."
              curl -X POST http://$HOST:$PORT/query?db=$DB --data-urlencode "q=DROP SERIES FROM /.*/"
          env:
            - name: HOST
              value: {{ .Values.influxdb.host }}
            - name: PORT
              value: {{ .Values.influxdb.port | quote }}
            - name: DB
              value: {{ .Values.influxdb.db }}
          {{- include "render-env-vars" (dict "service_name" "data_cleanup" "Values" .Values) }}
      restartPolicy: "OnFailure"
{{- end }}