# FIXME: This is likely not gonna work as expected and is naive implementation
# see also https://github.com/opencrvs/opencrvs-core/issues/7451
{{- if .Values.data_seeder.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: data-seeder
  name: data-seeder
spec:
  template:
    metadata:
      labels:
        app: data-seeder
    spec:
      containers:
        - name: data-seeder
          image: "ghcr.io/opencrvs/ocrvs-data-seeder:{{ .Values.image.tag }}"
          env:
            - name: AUTH_HOST
              value: "http://auth.{{ .Release.Namespace }}.svc.cluster.local:4040"
            - name: GATEWAY_HOST
              value: "http://gateway.{{ .Release.Namespace }}.svc.cluster.local:7070"
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- range $k, $v := .Values.data_seeder.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
      completions: 1 # Run the job once
      backoffLimit: 0 # Don't retry if the job fails
      restartPolicy: "OnFailure"
{{- end }}