{{- if .Values.data_seeder.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
  labels:
    app: data-seeder
  name: data-seeder
spec:
  template:
    metadata:
      labels:
        app: data-seeder
    spec:
      containers:
        - name: data-seeder
          image: "ghcr.io/opencrvs/ocrvs-data-seeder:{{ .Values.image.tag }}"
          env:
            - name: AUTH_HOST
              value: "http://auth.{{ .Release.Namespace }}.svc.cluster.local:4040"
            - name: GATEWAY_HOST
              value: "http://gateway.{{ .Release.Namespace }}.svc.cluster.local:7070"
            - name: COUNTRY_CONFIG_HOST
              value: http://countryconfig.{{ .Release.Namespace }}.svc.cluster.local:3040
          {{- include "render-env-vars" (dict "service_name" "data_seeder" "Values" .Values) }}
      restartPolicy: "OnFailure"
{{- end }}