---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: documents
  name: documents
spec:
  replicas: {{ .Values.documents.replicas }}
  selector:
    matchLabels:
      app: documents
  template:
    metadata:
      labels:
        app: documents
    spec:
      containers:
        - name: documents
          env:
            - name: COUNTRY_CONFIG_URL
              value: http://countryconfig.{{ .Release.Namespace }}.svc.cluster.local:3040
            - name: DOCUMENTS_PORT
              value: "9050"
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: MINIO_HOST
              value: {{ .Values.minio.host | quote }}
            - name: MINIO_PORT
              value: {{ .Values.minio.port | quote }}
            # TODO: MINIO: Check if we need http/https prefix here
            - name: MINIO_URL
              value: minio.{{ .Values.hostname }}
          {{- include "render-env-vars" (dict "service_name" "documents" "Values" .Values) }}
          image: "ghcr.io/opencrvs/ocrvs-documents:{{ .Values.image.tag }}"
          {{ include "resources-helper" (dict "service_name" "documents" "Values" .Values) | indent 10 }}
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
          ports:
            - containerPort: {{ .Values.documents.port }}
              protocol: TCP
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: {{ .Release.Name }}-cert-tls
          name: public-key

{{- include "service-helper" (dict "service_name" "documents" "Values" .Values) }}

{{- include "hpa-helper" (dict "service_name" "documents" "Values" .Values) }}

{{- include "pdb-helper" (dict "service_name" "documents" "Values" .Values) }}
