# TODO: Move as pre-deploy hook to opencrvs-service
# Change will allow to manage external database
{{- if not .Values.elasticsearch.credentials }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
  labels:
    app: elasticsearch-on-deploy
  name: elasticsearch-on-deploy
spec:
  template:
    metadata:
      labels:
        app: elasticsearch-on-deploy
    spec:
      containers:
        - name: elasticsearch-on-deploy
          command: ["/bin/bash", "/on-deploy.sh"]
          image: "mongo:4.4"
          env:
          {{- if .Values.elasticsearch.credentials.secret }}
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elasticsearch.credentials.secret }}
                  key: ELASTIC_PASSWORD
          {{- else if .Values.elasticsearch.credentials.password }}
            - name: ELASTIC_PASSWORD
              value: {{ .Values.elasticsearch.credentials.password }}
          {{- end }}
          # volumeMounts:
          #   - mountPath: /on-deploy.sh
          #     name: mongo-on-update-script
          #     subPath: on-deploy.sh
      # volumes:
      #   - name: mongo-on-update-script
      #     configMap:
      #       name: mongo-on-update-script
      restartPolicy: "OnFailure"
  {{- end }}
