{{- if .Values.elasticsearch.reindex_enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "4"
  labels:
    app: elasticsearch-reindex
  name: elasticsearch-reindex
spec:
  template:
    metadata:
      labels:
        app: elasticsearch-reindex
    spec:
{{ include "elasticsearch-reindex.podSpec" . | indent 2 }}

{{- if .Values.elasticsearch.cronjob.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-reindex
spec:
  schedule: "{{ .Values.elasticsearch.cronjob.schedule }}"
{{- if .Values.timezone }}
  timeZone: {{ .Values.timezone }}
{{- end }}
  jobTemplate:
    spec:
{{ include "elasticsearch-reindex.podSpec" . | indent 6 }}
{{- end }}
{{- end }}