{{- if .Values.elasticsearch.reindex_enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "4"
  labels:
    app: elasticsearch-reindex
  name: elasticsearch-reindex
spec:
  template:
    metadata:
      labels:
        app: elasticsearch-reindex
    spec:
      containers:
      {{- include "postgres-on-deploy.containerSpec" . | nindent 8 }}
      restartPolicy: "OnFailure"
    volumes:
      {{- include "postgres-on-deploy.volumes" . | nindent 8 }}
{{- end }}
