apiVersion: v1
kind: Service
metadata:
  labels:
    app: events
  name: events
spec:
  ports:
    - port: 5555
      targetPort: 5555
  selector:
    app: events
  type: {{ .Values.service_type }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: events-route
spec:
  entryPoints:
  {{- if .Values.ingress.ssl_enabled }}
    - websecure
  {{- else }}
    - web
  {{- end }}
  routes:
  - match: 'Host(`events.{{ .Values.hostname }}`)'
    kind: Rule
    services:
    - name: events
      namespace: {{ .Release.Namespace }}
      port: 5555
    middlewares:
      - name: sts-and-basic-response-headers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events
  name: events
spec:
  replicas: {{ .Values.events.replicas }}
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events
          image: "ghcr.io/opencrvs/ocrvs-events:{{ .Values.image.tag }}"
          env:
            - name: AUTH_URL
              value: "http://auth.{{ .Release.Namespace }}.svc.cluster.local:4040"
            - name: COUNTRY_CONFIG_URL
              value: "http://countryconfig.{{ .Release.Namespace }}.svc.cluster.local:3040"
            - name: DOCUMENTS_URL
              value: "http://documents.{{ .Release.Namespace }}.svc.cluster.local:9050"
            - name: ES_URL
              value: "http://{{ .Values.elasticsearch_host }}"  # TODO: Add username and password
            - name: ES_INDEX_PREFIX
              value: "events"
            - name: USER_MANAGEMENT_URL
              value: "http://user-mgnt.{{ .Release.Namespace }}.svc.cluster.local:3030/"
            - name: USER_MGNT_MONGO_URL
              value: mongodb://{{ .Values.mongodb_host }}/user-mgnt
            - name: EVENTS_MONGO_URL
              value: mongodb://{{ .Values.mongodb_host }}/events
            - name: MONGO_URL
              value: mongodb://{{ .Values.mongodb_host }}/events
          {{- include "render-env-vars" (dict "service_name" "events" "Values" .Values) }}
          ports:
            - containerPort: 5555
              protocol: TCP
      restartPolicy: Always
