apiVersion: v1
kind: Service
metadata:
  labels:
    app: hearth
  name: hearth
spec:
  clusterIP: None
  ports:
    - name: '3447'
      port: 3447
      targetPort: 3447
  selector:
    app: hearth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hearth
  name: hearth
spec:
  serviceName: hearth
  replicas: 1
  selector:
    matchLabels:
      app: hearth
  template:
    metadata:
      labels:
        app: hearth
    spec:
      containers:
        - env:
            - name: authentication__type
              value: disabled
            - name: idGenerator
              value: uuidv4
            - name: logger__level
              value: warn
          {{- if .Values.mongodb_noauth }}
            - name: mongodb__url
              value: mongodb://{{ .Values.mongodb_host }}/hearth-dev
          {{- end }}
            - name: server__fhirVersion
              value: stu3
          {{- if or .Values.hearth.secrets .Values.hearth.env .Values.env }}
          {{- include "render-env-vars" (dict "service_name" "hearth" "Values" .Values) }}
          {{- end }}
          image: opencrvs/hearth:1.1.0
          name: hearth
          ports:
            - containerPort: 3447
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: hearth-cm-public-key
              subPath: public-key.pem
            - mountPath: /src/hearth/lib/plugins/checkDuplicateTask.js
              name: hearth-cm-checkduplicetask
              subPath: checkDuplicateTask.js
            - mountPath: /src/hearth/config/queryparam-extensions.json
              name: hearth-cm-queryparam-extensions
              subPath: queryparam-extensions.json
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: hearth-cm-public-key
          name: hearth-cm-public-key
        - configMap:
            items:
              - key: checkDuplicateTask.js
                path: checkDuplicateTask.js
            name: hearth-cm-checkduplicetask
          name: hearth-cm-checkduplicetask
        - configMap:
            items:
              - key: hearth-queryparam-extensions.json
                path: queryparam-extensions.json
            name: hearth-cm-queryparam-extensions
          name: hearth-cm-queryparam-extensions
