---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: login-route
spec:
  entryPoints:
  {{- if .Values.ingress.ssl_enabled }}
    - websecure
  {{- end }}
  {{- if or .Values.ingress.tls_resolver (not .Values.ingress.ssl_enabled) }}
    - web
  {{- end }}
  routes:
  - match: 'Host(`login.{{ .Values.hostname }}`) || Host(`{{ .Values.hostname }}`)'
    kind: Rule
    services:
    - name: login
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.login.port }}
    middlewares:
      - name: sts-and-basic-response-headers
      - name: enable-compression
  {{- if .Values.ingress.tls_resolver }}
  tls:
    certResolver: {{ .Values.ingress.tls_resolver }}
  {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: login
  name: login
spec:
  replicas: {{ .Values.login.replicas }}
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: "ghcr.io/opencrvs/ocrvs-login:{{ .Values.image.tag }}"
          env:
            - name: CONTENT_SECURITY_POLICY_WILDCARD
              value: "*.{{ .Values.hostname }}"
            - name: COUNTRY_CONFIG_URL_INTERNAL
              value: http://countryconfig.{{ .Release.Namespace }}.svc.cluster.local:3040
          {{- include "render-env-vars" (dict "service_name" "login" "Values" .Values) }}
          {{ include "resources-helper" (dict "service_name" "login" "Values" .Values) | indent 10 }}
          ports:
            - containerPort: {{ .Values.login.container_port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              # /api/countryconfig/login-config.js is external service proxied by nginx
              # pod should be restarted once countryconfig is up
              path: /api/countryconfig/login-config.js
              port: {{ .Values.login.container_port }}
          readinessProbe:
            httpGet:
              # /api/countryconfig/login-config.js is external service proxied by nginx
              # pod should be restarted once countryconfig is up
              path: /api/countryconfig/login-config.js
              port: {{ .Values.login.container_port }}
      restartPolicy: Always

{{- include "service-helper" (dict "service_name" "login" "Values" .Values) }}

{{- include "hpa-helper" (dict "service_name" "login" "Values" .Values) }}

{{- include "pdb-helper" (dict "service_name" "login" "Values" .Values) }}
