apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics
  name: metrics
spec:
  ports:
    - port: 1050
      targetPort: 1050
  selector:
    app: metrics
  type: {{ .Values.service_type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrics
  name: metrics
spec:
  replicas:  {{ .Values.metrics.replicas }}
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
        - image: "ghcr.io/opencrvs/ocrvs-metrics:{{ .Values.image.tag }}"
          name: metrics
          env:
            - name: FHIR_URL
              value: {{ .Values.fhir_url | quote }}
            - name: METRICS_PORT  # Similar to PORT (Check if it's the same?)
              value: "1050"
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: CONFIG_API_URL
              value: http://config.{{ .Release.Namespace }}.svc.cluster.local:2021
            - name: COUNTRY_CONFIG_URL
              value: http://countryconfig.{{ .Release.Namespace }}.svc.cluster.local:3040
            - name: DOCUMENTS_URL
              value: http://documents.{{ .Release.Namespace }}.svc.cluster.local:9050
            - name: SEARCH_URL
              value: http://search.{{ .Release.Namespace }}.svc.cluster.local:9090/
            - name: USER_MANAGEMENT_URL
              value: http://user-mgnt.{{ .Release.Namespace }}.svc.cluster.local:3030
            - name: INFLUX_DB
              value: {{ .Values.influxdb.db | quote }}
            - name: INFLUX_HOST
              value: {{ .Values.influxdb.host | quote }}
            - name: INFLUX_PORT
              value: {{ .Values.influxdb.port | quote }}
            - name: DASHBOARD_MONGO_URL
              value: mongodb://{{ .Values.mongodb_host }}/performance
            - name: HEARTH_MONGO_URL
              value: mongodb://{{ .Values.mongodb_host }}/hearth-dev
            - name: MONGO_URL
              value: mongodb://{{ .Values.mongodb_host }}/metrics
          {{- include "render-env-vars" (dict "service_name" "metrics" "Values" .Values) }}
          ports:
            - containerPort: 1050
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: public-key
          name: public-key