# FIXME: This is likely not gonna work as expected and is naive implementation
# see also https://github.com/opencrvs/opencrvs-core/issues/7451
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: migration
  name: migration
spec:
  template:
    metadata:
      labels:
        app: migration
    spec:
      containers:
        - name: migration
          image: "ghcr.io/opencrvs/ocrvs-migration:{{ .Values.image.tag }}"
          env:
            - name: ES_HOST
              value: {{ .Values.elasticsearch_host | quote }}
            - name: SEARCH_URL
              value: http://search.{{ .Release.Namespace }}.svc.cluster.local:9090/
            - name: INFLUX_DB
              value: {{ .Values.influxdb.db | quote }}
            - name: INFLUX_HOST
              value: {{ .Values.influxdb.host | quote }}
            - name: INFLUX_PORT
              value: {{ .Values.influxdb.port | quote }}
            - name: MINIO_HOST
              value: {{ .Values.minio_host | quote }}
            - name: WAIT_HOSTS
              value: "{{ .Values.mongodb_host }}:27017,{{ .Values.influxdb.host }}:{{ .Values.influxdb.port }},{{ .Values.minio_host }}:3535,{{ .Values.elasticsearch_host }}"
          {{- range $k, $v := .Values.migration.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
          {{- end }}
      completions: 1 # Run the job once
      backoffLimit: 0 # Don't retry if the job fails
      restartPolicy: "OnFailure"