---
# TODO: REVIEW: Refactor job move to countryconfig assets
#       - delete setup-analytics.sh from helm chart
#       - remove configmap reference: postgres-on-update-script
#       - Remove related logic
# ETA: OpenCRVS v2.0
# Related PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/1184
# Related Issue: https://github.com/opencrvs/opencrvs-core/issues/11192
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
  labels:
    app: postgres-on-update-analytics
  name: postgres-on-update-analytics
spec:
  template:
    metadata:
      labels:
        app: postgres-on-update-analytics
    spec:
      initContainers:
        - name: copy-assets
          image: "{{ .Values.countryconfig.image.name }}:{{ .Values.countryconfig.image.tag }}-assets"
          command:
            - sh
            - -c
            - >
              [[ -d /assets/postgres/ ]] && cp -R /assets/postgres/* /data-assets/ ||
              cp -R /scripts/* /data-assets/;
              chmod +x /data-assets/*.sh || true
          volumeMounts:
            - name: assets
              mountPath: /data-assets
            # TODO: See comment at the top of this file
            - mountPath: /scripts
              name: postgres-on-update-script
      containers:
        - name: postgres-on-update-analytics
          command: ["bash", "-c", "/data-assets/setup-analytics.sh"]
          image: postgres:17
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.postgres.host }}
            - name: POSTGRES_PORT
              value: "5432"
          {{- if eq .Values.postgres.auth_mode "disabled" }}
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          {{- else }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.admin_user_secret_name }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.admin_user_secret_name }}
                  key: POSTGRES_PASSWORD
          {{- end }}
            - name: EVENTS_APP_ROLE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.users_secret }}
                  key: EVENTS_APP_POSTGRES_USER
            - name: EVENTS_APP_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.users_secret }}
                  key: EVENTS_APP_POSTGRES_PASSWORD
            - name: EVENTS_MIGRATOR_ROLE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.users_secret }}
                  key: EVENTS_MIGRATOR_POSTGRES_USER
            - name: EVENTS_MIGRATOR_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.users_secret }}
                  key: EVENTS_MIGRATOR_POSTGRES_PASSWORD
            - name: ANALYTICS_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.users_secret }}
                  key: EVENTS_ANALYTICS_POSTGRES_USER
            - name: ANALYTICS_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.users_secret }}
                  key: EVENTS_ANALYTICS_POSTGRES_PASSWORD
          {{- include "render-env-vars" (dict "service_name" "postgres_on_deploy" "Values" .Values) }}
          volumeMounts:
            - name: assets
              mountPath: /data-assets
      volumes:
        # TODO: See comment at the top of this file
        - name: postgres-on-update-script
          configMap:
            name: postgres-on-update-script
            defaultMode: 0755
        - name: assets
          emptyDir: {}
      restartPolicy: "OnFailure"
