
{{- if .Values.postgres.on_restore_cronjob.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: postgres
    job-type: restore
  name: postgres-on-db-restore
spec:
  schedule: "{{ .Values.postgres.on_restore_cronjob.schedule }}"
{{- if .Values.timezone }}
  timeZone: {{ .Values.timezone }}
{{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: postgres
            job-type: restore
        spec:
          restartPolicy: OnFailure
          containers:
            {{- include "postgres-on-deploy.containerSpec" . | nindent 12 }}
            {{- include "elasticsearch-reindex.containerSpec" . | nindent 12 }}
          volumes:
            {{- include "postgres-on-deploy.volumes" . | nindent 10 }}
            {{- include "elasticsearch-reindex.volumes" . | nindent 10 }}
{{- end }}
 