---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: search
  name: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: "ghcr.io/opencrvs/ocrvs-search:{{ .Values.image.tag }}"
          env:
            - name: FHIR_URL
              value: {{ .Values.fhir_url | quote | default "http://hearth:3447/fhir" }}
            - name: APPLICATION_CONFIG_URL
              value: http://config.{{ .Release.Namespace }}.svc.cluster.local:2021
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
          {{- if .Values.elasticsearch.noauth }}
            - name: ES_HOST
              value: "{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}"
          {{- end}}
            - name: USER_MANAGEMENT_URL
              value: http://user-mgnt.{{ .Release.Namespace }}.svc.cluster.local:3030/
          {{- if .Values.mongodb_noauth }}
            - name: HEARTH_MONGO_URL
              value: mongodb://{{ .Values.mongodb_host }}/hearth-dev
          {{- end }}
          {{- include "render-env-vars" (dict "service_name" "search" "Values" .Values) }}
          {{ include "resources-helper" (dict "service_name" "search" "Values" .Values) | indent 10 }}
          ports:
            - containerPort: {{ .Values.search.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping # FIXME: not real healthz, just checking if http server is up x
              port: {{ .Values.search.port }}
          readinessProbe:
            httpGet:
              path: /ping # FIXME: not real healthz, just checking if http server is up
              port: {{ .Values.search.port }}
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: {{ .Release.Name }}-cert-tls
          name: public-key

{{- include "service-helper" (dict "service_name" "search" "Values" .Values) }}

{{- include "hpa-helper" (dict "service_name" "search" "Values" .Values) }}

{{- include "pdb-helper" (dict "service_name" "search" "Values" .Values) }}
