---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-mgnt
  name: user-mgnt
spec:
  replicas: {{ .Values.user_mgnt.replicas }}
  selector:
    matchLabels:
      app: user-mgnt
  template:
    metadata:
      labels:
        app: user-mgnt
    spec:
      containers:
        - name: user-mgnt
          image: "ghcr.io/opencrvs/ocrvs-user-mgnt:{{ .Values.image.tag }}"
          env:
            - name: FHIR_URL
              value: {{ .Values.fhir_url | quote }}
            - name: APPLICATION_CONFIG_URL
              value: http://config.{{ .Release.Namespace }}.svc.cluster.local:2021
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: HOST
              value: 0.0.0.0
            - name: METRICS_URL
              value: http://metrics.{{ .Release.Namespace }}.svc.cluster.local:1050
            - name: NOTIFICATION_SERVICE_URL
              value: http://notification.{{ .Release.Namespace }}.svc.cluster.local:2020/
            - name: DOCUMENTS_URL
              value: http://documents.{{ .Release.Namespace }}.svc.cluster.local:9050
            - name: MONGO_URL
              value: mongodb://{{ .Values.mongodb_host }}/user-mgnt
            - name: COUNTRY_CONFIG_URL
              value: {{ include "render-external-url" (dict "service_name" "user_mgnt" "Values" .Values) }}
          {{- include "render-env-vars" (dict "service_name" "user_mgnt" "Values" .Values) }}
          ports:
            - containerPort: {{ .Values.user_mgnt.port }}
              protocol: TCP
          {{ include "resources-helper" (dict "service_name" "user_mgnt" "Values" .Values) | indent 10 }}
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: {{ .Release.Name }}-cert-tls
          name: public-key

{{- include "service-helper" (dict "service_name" "user-mgnt" "Values" .Values) }}

{{- include "hpa-helper" (dict "service_name" "user-mgnt" "Values" .Values) }}

{{- include "pdb-helper" (dict "service_name" "user-mgnt" "Values" .Values) }}
