---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workflow
  name: workflow
spec:
  replicas: {{ .Values.workflow.replicas }}
  selector:
    matchLabels:
      app: workflow
  template:
    metadata:
      labels:
        app: workflow
    spec:
      containers:
        - name: workflow
          image: "ghcr.io/opencrvs/ocrvs-workflow:{{ .Values.image.tag }}"
          env:
            - name: FHIR_URL
              value: {{ .Values.fhir_url | quote | default "http://hearth:3447/fhir" }}
            - name: APPLICATION_CONFIG_URL
              value: http://config.{{ .Release.Namespace }}.svc.cluster.local:2021
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: COUNTRY
              value: bgd
            - name: AUTH_URL
              value: http://auth.{{ .Release.Namespace }}.svc.cluster.local:4040
            - name: COUNTRY_CONFIG_URL
              value: http://countryconfig.{{ .Release.Namespace }}.svc.cluster.local:3040
            - name: DOCUMENTS_URL
              value: http://documents.{{ .Release.Namespace }}.svc.cluster.local:9050
            - name: METRICS_URL
              value: http://metrics.{{ .Release.Namespace }}.svc.cluster.local:1050
            - name: NOTIFICATION_SERVICE_URL
              value: http://notification.{{ .Release.Namespace }}.svc.cluster.local:2020/
            - name: SEARCH_URL
              value: http://search.{{ .Release.Namespace }}.svc.cluster.local:9090/
            - name: USER_MANAGEMENT_URL
              value: http://user-mgnt.{{ .Release.Namespace }}.svc.cluster.local:3030/
            - name: WEBHOOKS_URL
              value: http://webhooks.{{ .Release.Namespace }}.svc.cluster.local:2525/
          {{- include "render-env-vars" (dict "service_name" "workflow" "Values" .Values) }}
          {{ include "resources-helper" (dict "service_name" "workflow" "Values" .Values) | indent 10 }}
          ports:
            - containerPort: {{ .Values.workflow.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping # FIXME: not real healthz, just checking if http server is up x
              port: {{ .Values.workflow.port }}
          readinessProbe:
            httpGet:
              path: /ping # FIXME: not real healthz, just checking if http server is up
              port: {{ .Values.workflow.port }}
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: {{ .Release.Name }}-cert-tls
          name: public-key

{{- include "service-helper" (dict "service_name" "workflow" "Values" .Values) }}

{{- include "hpa-helper" (dict "service_name" "workflow" "Values" .Values) }}

{{- include "pdb-helper" (dict "service_name" "workflow" "Values" .Values) }}
