- name: Check if /tmp/id_ed25519_backup exists
  stat:
    path: /tmp/id_ed25519_backup
  register: backup_key_file
- name: Read the backup SSH key file
  ansible.builtin.slurp:
    src: /tmp/id_ed25519_backup
  register: ssh_key_file
  when: backup_key_file.stat.exists
- name: Ensure namespace opencrvs-deps-{{ k8s_cluster_env }} exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: opencrvs-deps-{{ k8s_cluster_env }}
    state: present
  when: backup_key_file.stat.exists
- name: Ensure the Kubernetes secret for backup exists
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    state: present
    namespace: "opencrvs-deps-{{ k8s_cluster_env }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ backup_server_ssh_credentials_secret }}"
      type: Opaque
      data:
        ssh_key: "{{ ssh_key_file.content | default('') }}"
        user: "{{ backup_server_user | b64encode }}"
        host: "{{ hostvars[groups['backup'][0]]['ansible_host'] | b64encode }}"
  when:
    - "'backup' in groups"
    - "groups['backup'] | length > 0"
    - backup_key_file.stat.exists