- name: Ensure namespace opencrvs-{{ k8s_cluster_env }} exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: opencrvs-{{ k8s_cluster_env }}
    state: present
- name: Create Docker Hub secret (server defaults)
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "dockerhub-credentials"
        namespace: "opencrvs-{{ k8s_cluster_env }}"
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ dockerconfig | to_json | b64encode }}"
  vars:
    dockerconfig:
      auths:
        "https://index.docker.io/v1/":  # Docker Hub default
          username: "{{ docker_username }}"
          password: "{{ docker_password }}"
          auth: "{{ (docker_username + ':' + docker_password) | b64encode }}"