- name: Remove Docker's old versions if installed
  apt:
    name: "{{ item }}"
    state: absent
    purge: true
  loop:
    - docker
    - docker-ce
    - docker-ce-cli
    - docker-buildx-plugin
    - docker-ce-rootless-extras
    - docker-compose-plugin
    - docker-engine
    - python3-docker
    - docker.io
    - containerd
    - runc
  ignore_errors: true

- name: Remove Docker's official GPG key if it exists
  shell: rm -f /etc/apt/trusted.gpg.d/docker.gpg
  ignore_errors: true

- name: Add Docker's official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg

- name: Add Docker repository
  shell: add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Install containerd
  shell: |
    apt-get update
    apt-get install -y containerd.io

- name: Create containerd configuration directory
  shell: mkdir -p /etc/containerd

- name: Generate containerd default configuration
  shell: |
    containerd config default | tee /etc/containerd/config.toml

- name: Configure containerd to use systemd cgroup driver
  shell: sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

- name: Restart and enable containerd service
  shell: |
    systemctl restart containerd
    systemctl enable containerd