- name: 'Install UFW'
  apt:
    name: ufw
    state: present

- name: "Show UFW status before changes"
  shell: ufw status numbered

- name: Delete existing UFW rules managed by Ansible
  shell: |
    ufw status numbered \
      | grep 'Managed by OpenCRVS Ansible' \
      | grep -vE '\b(22|80|443)(/tcp|/udp)?\b' \
      | tac \
      | sed -n 's/^\[\s*\([0-9]\+\)\].*/\1/p' \
      | while read rule; do
          echo "Deleting UFW rule #$rule"
          ufw --force delete "$rule"
        done
  changed_when: true

- name: "Allow Traefik (ports 80, 443) only on master"
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    comment: "Managed by OpenCRVS Ansible"
  loop: [80, 443]
  when: "'master' in group_names"

- name: "Allow Kubernetes API server access only from allowed CIDRs on master"
  ufw:
    rule: allow
    port: "6443"
    proto: tcp
    from_ip: "{{ item }}"
    comment: "Managed by OpenCRVS Ansible"
  loop: >-
    {{
      kube_api_allowed_cidrs.split(',')
      | map('trim')
      | list
    }}
  when: "'master' in group_names"

- name: "Allow ssh connections"
  ufw:
    rule: allow
    port: "22"
    proto: tcp
    comment: "Managed by OpenCRVS Ansible"
# Kube and overlay ports for all nodes, adjust as needed
- name: "Allow cluster communication ports"
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    from_ip: "{{ kube_cluster_node_cidr }}"
    comment: "Managed by OpenCRVS Ansible"
  loop:
    # Kubernetes API server (required by control plane & nodes)
    - { port: 6443, proto: "tcp" }
    # etcd API server (required by control plane only)
    - { port: 2379, proto: "tcp" } # etcd client API
    - { port: 2380, proto: "tcp" } # etcd peer communication
    # Kubelet API (required for all nodes)
    - { port: 10250, proto: "tcp" }
    # kube-scheduler (control plane only)
    - { port: 10251, proto: "tcp" }
    # kube-controller-manager (control plane only)
    - { port: 10252, proto: "tcp" }
    # Overlay network (Calico/Weave/Flannel, if used—verify your CNI and usage)
    - { port: 7946, proto: "tcp" }   # Used by some CNIs (e.g., Flannel, Weave)
    - { port: 7946, proto: "udp" }   # Used by some CNIs (e.g., Flannel, Weave)
    - { port: 8472, proto: "udp" }   # VXLAN (Flannel/Calico; verify if needed)
    - { port: 4789, proto: "udp" }   # VXLAN (Calico; verify if needed)
    - { port: 179, proto: "tcp" }    # BGP (Calico)
    - { port: 179, proto: "udp" }    # BGP (Calico)
    # Expose traefik on node port
    # Rules are required for internet facing load balancer (if exists)
    - { port: 30080, proto: "tcp" }  # NodePort HTTP
    - { port: 30443, proto: "tcp" }  # NodePort HTTPS
  ignore_errors: yes

- name: "Allow traffic on Calico interfaces"
  community.general.ufw:
    rule: allow
    interface_in: "{{ item }}"
    comment: "Managed by OpenCRVS Ansible"
  loop:
    - cali+
    - vxlan.calico
  ignore_errors: yes

- name: "Enable UFW with deny by default"
  ufw:
    state: enabled
    default: deny
    direction: incoming
