apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-ssl
  namespace: opencrvs-deps-dev
spec:
  # Secret names are always required.
  secretName: minio-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
  - minio.k8s.opencrvs.dev