hostname: test-k8s.opencrvs.dev
storage_type: host_path
node_selector:
  role: data1

ingress:
  tls_resolver: letsencrypt

minio:
  use_default_credentials: false

elasticsearch:
  use_default_credentials: false
  node_selector:
    role: data2
mongodb:
  use_default_credentials: false

postgres:
  use_default_credentials: false

monitoring:
  enabled: true

backup:
  enabled: true