ingress:
  ssl_enabled: false

# On local environment services are exposed at NodePort as well and are available from Tilt
# To access service you need to click on the service name in Tilt UI:
service_type: LoadBalancer

# Horizontal Pod Autoscaler (HPA) configuration:
# Disabled by default for local environment.
hpa:
  enabled: false

# Pod Disruption Budget (PDB) configuration:
# Disabled by default for local environment.
pdb:
  enabled: false

# Dashboards is disabled by default to allow easy deployment on Apple Silicon
# If you are using x86 device, feel free to enable:
dashboards:
  enabled: false