# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
---
- hosts: master
  gather_facts: yes
  ignore_unreachable: false
  tasks:
    - include_tasks:
        file: tasks/all/checks-k8s.yml
        apply:
          tags:
            - checks
            - k8s
      tags:
        - checks
        - k8s

- hosts: all
  become: yes
  gather_facts: yes
  ignore_unreachable: false
  become_method: sudo
  tasks:
    - include_tasks:
        file: tasks/all/checks-system.yml
        apply:
          tags:
            - checks
      tags:
        - checks

    - include_tasks:
        file: tasks/all/updates.yml
        apply:
          tags:
            - updates
      tags:
        - updates
    - include_tasks:
        file: tasks/all/users.yml
        apply:
          tags:
            - users
      tags:
        - users

    - include_tasks:
        file: tasks/all/tools.yml
        apply:
          tags:
            - tools
      tags:
        - tools

    - include_tasks:
        file: tasks/all/fail2ban.yml
        apply:
          tags:
            - fail2ban
      tags:
        - fail2ban

# Backup server setup goes before k8s cluster
- import_playbook: backup.yml

# This part of playbook contains mostly kubernetes stuff
- import_playbook: k8s.yml
