
# Dependencies configuration for OpenCRVS services
# Redis hostname
redis_host: redis.opencrvs-deps-dev.svc.cluster.local
# TODO: Clarify if we can define port

# Elasticsearch hostname
# TODO: Should we define port as separate variable?
# elasticsearch:
#     host: elasticsearch.opencrvs-deps-dev.svc.cluster.local
#     port: 9200
elasticsearch_host: elasticsearch.opencrvs-deps-dev.svc.cluster.local:9200

influxdb:
  host: influxdb-0.influxdb.opencrvs-deps-dev.svc.cluster.local
  port: 8086
  db: ocrvs
# TODO: Add description
fhir_url: http://hearth.opencrvs-deps-dev.svc.cluster.local:3447/fhir

# Minio hostname
minio_host: minio-0.minio.opencrvs-deps-dev.svc.cluster.local

# MongoDB hostname
mongodb_host: mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local

# Defined at global level
# SENTRY_DSN: https://...@o309867.ingest.sentry.io/....
sentry_dsn: ""

# Hostname for OpenCRVS (without wildcard or subdomain)
# hostname: opencrvs.localhost


env:
  QA_ENV: true
  # APN_SERVICE_URL: http://dependencies_apm-server:8200

client:
  replicas: 1
auth:
  replicas: 1
components:
  replicas: 1
config:
  replicas: 1
  env:
    LOG_LEVEL: "debug"
    DOMAIN: "*"
    CHECK_INVALID_TOKEN: true
    HEARTH_MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/hearth-dev
    MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/application-config
    NODE_ENV: production
countryconfig:
  image:
    name: opencrvs/ocrvs-countryconfig
    tag: latest
  replicas: 1
  env:
    ALERT_EMAIL: kibana-alerts-aaaafy3oysoklmlsqcjxad7rfi@opencrvsworkspace.slack.com
    # "APN_SERVICE_URL=http://apm-server:8200",

    CHECK_INVALID_TOKEN: true
    COUNTRY_CONFIG_HOST: "0.0.0.0"
    CERT_PUBLIC_KEY_PATH: /secrets/public-key.pem
    CONFIG_MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/application-config

    # TODO: Replace with {{ .Values.hostname }}
    INFOBIP_API_KEY: ""
    INFOBIP_GATEWAY_ENDPOINT: ""
    INFOBIP_SENDER_ID: ""

    MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/user-mgnt
    NODE_ENV: production
    NOTIFICATION_TRANSPORT: email
    QA_ENV: true
    SENDER_EMAIL_ADDRESS: noreply@opencrvs.org
    SMTP_HOST: localhost
    SMTP_PASSWORD: ""
    SMTP_PORT: 587
    SMTP_SECURE: "false"
    SMTP_USERNAME: apikey
dashboards:
  replicas: 1
data_seeder:
  enabled: false
  env:
    # TODO: Fix variable name
    COUNTRY_CONFIG_HOST: "http://countryconfig.opencrvs-services-dev.svc.cluster.local:3040"
    SUPER_USER_PASSWORD: "password"
    ACTIVATE_USERS: "true"
documents:
  replicas: 1
gateway:
  replicas: 1
  env:
    CERT_PUBLIC_KEY_PATH: "/secrets/public-key.pem"
    CHECK_INVALID_TOKEN: "true"
    CONFIG_SMS_CODE_EXPIRY_SECONDS: "600"
    CONFIG_TOKEN_EXPIRY_SECONDS: "604800"

    MINIO_BUCKET: "ocrvs"
    # # TODO: Check usage
    # NODE_ENV: "development"
    # LOGIN_URL: "https://login.opencrvs.localhost"
    NODE_ENV: production

    COUNTRY: FAR
    DISABLE_RATE_LIMIT: "true"
    # # TODO: Check usage
    DOMAIN: "opencrvs.localhost"

    HOST: "0.0.0.0"
    LANGUAGES: "en,fr"

    QA_ENV: "true"
    # "APN_SERVICE_URL=http://dependencies_apm-server:8200",

login:
  replicas: 1

metrics:
  replicas: 1
  env:
    DASHBOARD_MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/performance
    HEARTH_MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/hearth-dev
    MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/metrics
notification:
  env:
    COUNTRY: bgd
    MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/notification
  replicas: 1
search:
  replicas: 1
  env:
    HEARTH_MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/hearth-dev
userMgnt:
  replicas: 1
  env:
    MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/user-mgnt
webhooks:
  replicas: 1
  env:
    MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/webhooks
workflow:
  replicas: 1
scheduler:
  env:
    OPENHIM_MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/openhim-dev
events:
  replicas: 1
  env:
    USER_MGNT_MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/user-mgnt
    EVENTS_MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/events
    MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/events
migration:
  env:
    APPLICATION_CONFIG_MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/application-config
    USER_MGNT_MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/user-mgnt
    PERFORMANCE_MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/performance
    HEARTH_MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/hearth-dev
    OPENHIM_MONGO_URL: mongodb://mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local/openhim-dev
hostname: farajaland.com
dev_mode: false