
# Dependencies configuration for OpenCRVS services
# Redis hostname
redis_host: redis.opencrvs-deps-dev.svc.cluster.local
# TODO: Clarify if we can define port

# Elasticsearch hostname
# TODO: Should we define port as separate variable?
# elasticsearch:
#     host: elasticsearch.opencrvs-deps-dev.svc.cluster.local
#     port: 9200
elasticsearch_host: elasticsearch.opencrvs-deps-dev.svc.cluster.local:9200

influxdb:
  host: influxdb-0.influxdb.opencrvs-deps-dev.svc.cluster.local
  port: 8086
  db: ocrvs
# TODO: Add description
fhir_url: http://hearth.opencrvs-deps-dev.svc.cluster.local:3447/fhir

# Minio hostname
minio:
  host: minio-0.minio.opencrvs-deps-dev.svc.cluster.local
  port: 3535

# MongoDB hostname
mongodb_host: mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local

# Defined at global level
# SENTRY_DSN: https://...@o309867.ingest.sentry.io/....
sentry_dsn: ""

# Hostname for OpenCRVS (without wildcard or subdomain)
# hostname: opencrvs.localhost


env:
  QA_ENV: true
  # APN_SERVICE_URL: http://dependencies_apm-server:8200

client:
  replicas: 1
auth:
  replicas: 1
components:
  replicas: 1
config:
  replicas: 1
  env:
    LOG_LEVEL: "debug"
    DOMAIN: "*"
    CHECK_INVALID_TOKEN: true
    NODE_ENV: production
countryconfig:
  image:
    name: opencrvs/ocrvs-countryconfig
    tag: latest
  replicas: 1
  env:
    ALERT_EMAIL: kibana-alerts-aaaafy3oysoklmlsqcjxad7rfi@opencrvsworkspace.slack.com
    CHECK_INVALID_TOKEN: true
    INFOBIP_API_KEY: ""
    INFOBIP_GATEWAY_ENDPOINT: ""
    INFOBIP_SENDER_ID: ""

    NODE_ENV: production
    NOTIFICATION_TRANSPORT: email

    SENDER_EMAIL_ADDRESS: noreply@opencrvs.org
    SMTP_HOST: localhost
    SMTP_PASSWORD: ""
    SMTP_PORT: 587
    SMTP_SECURE: "false"
    SMTP_USERNAME: apikey
dashboards:
  replicas: 1
  env:
    OPENCRVS_METABASE_ADMIN_EMAIL: ""
    OPENCRVS_METABASE_ADMIN_PASSWORD: ""
    OPENCRVS_METABASE_DB_AUTH_DB: ""
    OPENCRVS_METABASE_DB_PASS: ""
    OPENCRVS_METABASE_DB_USER: ""
    OPENCRVS_METABASE_MAP_NAME: Full country
    OPENCRVS_METABASE_MAP_REGION_KEY: State
    OPENCRVS_METABASE_MAP_REGION_NAME: State
    OPENCRVS_METABASE_SITE_NAME: OpenCRVS Dashboards
    OPENCRVS_METABASE_ADMIN_EMAIL: user@opencrvs.org
    OPENCRVS_METABASE_ADMIN_PASSWORD: m3tabase

data_seeder:
  enabled: false
  env:
    SUPER_USER_PASSWORD: "password"
    ACTIVATE_USERS: "true"
documents:
  replicas: 1
gateway:
  replicas: 1
  env:
    CHECK_INVALID_TOKEN: "true"
    CONFIG_SMS_CODE_EXPIRY_SECONDS: "600"
    CONFIG_TOKEN_EXPIRY_SECONDS: "604800"

    MINIO_BUCKET: "ocrvs"

    NODE_ENV: production

    COUNTRY: FAR
    DISABLE_RATE_LIMIT: "true"
    # # TODO: Check usage
    DOMAIN: "opencrvs.localhost"

    LANGUAGES: "en,fr"

login:
  replicas: 1

metrics:
  replicas: 1

notification:
  env:
    COUNTRY: bgd
  replicas: 1
search:
  replicas: 1

userMgnt:
  replicas: 1

webhooks:
  replicas: 1

workflow:
  replicas: 1

events:
  replicas: 1

hostname: farajaland.com
dev_mode: false
