hostname: k8s.opencrvs.dev

minio:
  # TODO: Revisit naming convention
  # use_default_credentials could be applied to redis and other services as well
  use_default_credentials: false

# redis:
#   acl:
#     enabled: true
