name: Deploy Application on k8s
run-name: "Deploy OpenCRVS on k8s (core: ${{ github.event.inputs.core-image-tag }}, countryconfig: ${{ github.event.inputs.countryconfig-image-tag }})"
on:
    workflow_dispatch:
      inputs:
        core-image-tag:
          description: "Tag of the core image"
          required: true
          default: "develop"
        countryconfig-image-tag:
          description: "Tag of the countryconfig image"
          required: true
          default: "develop"
        environment:
          description: "Target environment"
          required: true
          default: "demo"
          type: choice
          options:
            - dev
            - demo
    # push:
    #     branches: ["develop"]
jobs:
  deploy:
    env:
      ENV: ${{ github.event.inputs.environment }}
      CORE_IMAGE_TAG: ${{ github.event.inputs.core-image-tag }}
      COUNTRYCONFIG_IMAGE_TAG: ${{ github.event.inputs.countryconfig-image-tag }}
    runs-on: [self-hosted]
    # TEMPORARY COMMENTED
    # environment: ${{ github.event.inputs.environment }}

    steps:
      # FYI: Repository is needed only due to single file: infrastructure/dev/opencrvs-services/values.yaml
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print deployment parameters
        run: |
          echo "Environment: $ENV"
          echo "Core Image: $CORE_IMAGE_TAG"
          echo "Country Config Image: $COUNTRYCONFIG_IMAGE_TAG"
      - name: Create namespace
        run: |
          kubectl create namespace opencrvs-${ENV} || echo "Namespace already exists"
      - name: Copy secrets from dependencies into application namespace
        run: |
          secrets=(
            "redis-opencrvs-users"
            "minio-opencrvs-users"
          )
          for secret in "${secrets[@]}"; do
            kubectl get secret $secret -n opencrvs-deps-${ENV} -o yaml \
            | sed "s#namespace: opencrvs-deps-${ENV}#namespace: opencrvs-${ENV}#" \
            | grep -vE 'resourceVersion|uid|creationTimestamp' \
            | kubectl apply -n opencrvs-${ENV} -f - \
            || echo "Secret $secret doesn't exist in opencrvs-deps-${ENV} namespace"
          done
      - name: Deploy with Helm
        run: |
          helm upgrade --install opencrvs oci://ghcr.io/opencrvs/opencrvs-services \
            --namespace "opencrvs-${ENV}" \
            -f infrastructure/${ENV}/opencrvs-services/values.yaml \
            --create-namespace \
            --set core.image.tag="$CORE_IMAGE_TAG" \
            --set countryconfig.image.tag="$COUNTRYCONFIG_IMAGE_TAG" \
            --set environment="$ENV"
