name: Deploy Application on k8s
run-name: "Deploy OpenCRVS on k8s (core: ${{ inputs.core-image-tag }}, country: ${{ inputs.countryconfig-image-tag }})"
on:
    workflow_dispatch:
      inputs:
        core-image-tag:
          description: "Tag of the core image"
          required: true
          default: "develop"
        countryconfig-image-tag:
          description: "Tag of the countryconfig image"
          required: true
          default: "develop"
        environment:
          description: "Target environment"
          required: true
          default: "demo"
          type: choice
          options:
            - dev
            - demo
    workflow_call:
      inputs:
        core-image-tag:
          type: string
        countryconfig-image-tag:
          type: string
        environment:
          type: string

jobs:
  deploy:
    env:
      ENV: ${{ inputs.environment }}
      CORE_IMAGE_TAG: ${{ inputs.core-image-tag }}
      COUNTRYCONFIG_IMAGE_TAG: ${{ inputs.countryconfig-image-tag }}
    runs-on: [self-hosted]
    # runs-on: ubuntu-latest

    steps:
      # FYI: Repository is needed only due to single file: examples/dev/opencrvs-services/values.yaml
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print deployment parameters
        run: |
          echo "Environment: $ENV"
          echo "Core Image: $CORE_IMAGE_TAG"
          echo "Country Config Image: $COUNTRYCONFIG_IMAGE_TAG"
      - name: Create namespace
        run: |
          kubectl create namespace opencrvs-${ENV} || echo "Namespace already exists"
      - name: Copy secrets from dependencies into application namespace
        run: |
          secrets=(
            "elasticsearch-admin-user"
            "redis-opencrvs-users"
            "minio-opencrvs-users"
            "mongodb-admin-user"
          )
          for secret in "${secrets[@]}"; do
            kubectl get secret $secret -n opencrvs-deps-${ENV} -o yaml \
            | sed "s#namespace: opencrvs-deps-${ENV}#namespace: opencrvs-${ENV}#" \
            | grep -vE 'resourceVersion|uid|creationTimestamp' \
            | kubectl apply -n opencrvs-${ENV} -f - \
            || echo "Secret $secret doesn't exist in opencrvs-deps-${ENV} namespace"
          done
      # FIXME:
      # In generic workflow we should use environment variables or ...
      # but not examples/e2e/opencrvs-services/values.yaml
      - name: Deploy with Helm
        run: |
          helm upgrade --install opencrvs oci://ghcr.io/opencrvs/opencrvs-services \
            --namespace "opencrvs-${ENV}" \
            -f examples/e2e/opencrvs-services/values.yaml \
            --create-namespace \
            --set image.tag="$CORE_IMAGE_TAG" \
            --set countryconfig.image.tag="$COUNTRYCONFIG_IMAGE_TAG" \
            --set hostname=$ENV.k8s-e2e.opencrvs.dev \
            --set environment="$ENV"
