name: Deploy Dependencies on k8s
on:
    workflow_dispatch:
      inputs:
        environment:
          description: "Target environment"
          required: true
          default: "demo"
          type: choice
          options:
            - dev
            - demo
jobs:
  deploy:
    env:
      ENV: ${{ github.event.inputs.environment }}
    # TODO: Add option to choose between self-hosted and default runners
    runs-on: [self-hosted]
    # TEMPORARY COMMENTED
    # environment: ${{ github.event.inputs.environment }}

    steps:
      # FYI: Repository is needed only due to single file: infrastructure/dev/dependenciess/values.yaml
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print deployment parameters
        run: |
          echo "Environment: $ENV"

      - name: Deploy with Helm
        run: |
          helm upgrade --install opencrvs-deps oci://ghcr.io/opencrvs/opencrvs-dependencies-chart:0.1.1 \
            --namespace "opencrvs-deps-${ENV}" \
            -f infrastructure/${ENV}/dependencies/values.yaml \
            --create-namespace \
            --set environment="$ENV"
