name: Deploy Dependencies on k8s
on:
    workflow_dispatch:
      inputs:
        environment:
          description: "Target environment"
          required: true
          default: "dev"
          type: choice
          options:
            - dev

jobs:
  deploy:
    env:
      ENV: ${{ inputs.environment }}
    runs-on: [self-hosted]
    steps:
      - name: 
        run: |
          helm upgrade --install traefik oci://ghcr.io/traefik/helm/traefik \
            --namespace traefik \
            --create-namespace \
            -f https://raw.githubusercontent.com/opencrvs/infrastructure/refs/heads/k8s-provision/examples/${ENV}/traefik/values.yaml
      - name: Install OpenCRVS dependencies
        run: |
          helm upgrade --install opencrvs-deps oci://ghcr.io/opencrvs/opencrvs-dependencies-chart \
            --namespace "opencrvs-deps-${ENV}" \
            -f https://raw.githubusercontent.com/opencrvs/infrastructure/refs/heads/k8s-provision/examples/${ENV}/dependencies/values.yaml \
            --create-namespace \
            --set storage_type=host_path \
            --atomic
