name: Sync GitHub env to Kubernetes
run-name: "Sync GitHub env to k8s for ${{ inputs.environment }} (${{ inputs.namespace_template }})"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "staging"
        type: choice
        options:
          - production
          - staging
      namespace_template:
        description: "Secrets mapping template"
        default: "opencrvs"
        type: choice
        options:
          - opencrvs
          - opencrvs-deps
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
      namespace_template:
        type: string
        default: opencrvs

jobs:
  get-restore-env-name:
    name: Determine restore environment name
    outputs:
      restore_env_name: ${{ steps.set-restore-env.outputs.restore-env-name }}
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Set restore environment name
        id: set-restore-env
        run: |
          if [ "${{ vars.RESTORE_ENVIRONMENT_NAME }}" != "false" ]; then
          echo "restore-env-name=${{ vars.RESTORE_ENVIRONMENT_NAME }}"
          echo "restore-env-name=${{ vars.RESTORE_ENVIRONMENT_NAME }}" >> $GITHUB_OUTPUT
          fi
      - name: "Env name: ${{ steps.set-restore-env.outputs.restore-env-name }}"
        environement: ${{ steps.set-restore-env.outputs.restore-env-name }}
        run: |
          echo "Determined restore environment name: ${{ steps.set-restore-env.outputs.restore-env-name }}"
  get-secrets:
    needs: get-restore-env-name
    if: needs.get-restore-env-name.outputs.restore_env_name != 'false'
    name: Get secrets for restore environment ${{ needs.get-restore-env-name.outputs.restore_env_name}}
    runs-on: ubuntu-24.04
    environment: ${{ needs.get-restore-env-name.outputs.restore_env_name }}
    outputs:
      BACKUP_ENCRYPTION_PASSPHRASE: ${{ steps.fetch-secrets.outputs.BACKUP_ENCRYPTION_PASSPHRASE }}
      BACKUP_HOST_PRIVATE_KEY: ${{ steps.fetch-secrets.outputs.BACKUP_HOST_PRIVATE_KEY }}
      BACKUP_HOST: ${{ steps.fetch-secrets.outputs.BACKUP_HOST }}
      BACKUP_SERVER_USER: ${{ steps.fetch-secrets.outputs.BACKUP_SERVER_USER }}
    steps:
      - name: Fetch secrets for restore environment
        run: |
          echo "Fetching secrets for environment: ${{ needs.get-restore-env-name.outputs.restore_env_name }} ${{toJSON(secrets)}}}}"
          echo "${{ toJSON(vars) }}"
          # Add commands here to fetch and store secrets as needed
  # get-backup-user:
  #   name: Get backup user
  #   uses: ./.github/workflows/get-secret-from-environment.yml
  #   with:
  #     secret_name: 'BACKUP_SERVER_USER'
  #     env_name: ${{ inputs.restore_environment }}
  #   secrets:
  #     gh_token: ${{ secrets.GH_TOKEN }}
  #     encryption_key: ${{ secrets.GH_ENCRYPTION_PASSWORD }}

  # get-backup-host:
  #   name: Get backup host
  #   uses: ./.github/workflows/get-secret-from-environment.yml
  #   with:
  #     secret_name: 'BACKUP_HOST'
  #     env_name: ${{ inputs.restore_environment }}
  #   secrets:
  #     gh_token: ${{ secrets.GH_TOKEN }}
  #     encryption_key: ${{ secrets.GH_ENCRYPTION_PASSWORD }}

  # get-backup-ssh-key:
  #   name: Get backup SSH key
  #   uses: ./.github/workflows/get-secret-from-environment.yml
  #   with:
  #     secret_name: 'BACKUP_HOST_PRIVATE_KEY'
  #     env_name: ${{ inputs.restore_environment }}
  #   secrets:
  #     gh_token: ${{ secrets.GH_TOKEN }}
  #     encryption_key: ${{ secrets.GH_ENCRYPTION_PASSWORD }}

  # get-backup-encryption-key:
  #   name: Get backup encryption key
  #   uses: ./.github/workflows/get-secret-from-environment.yml
  #   with:
  #     secret_name: 'BACKUP_ENCRYPTION_PASSPHRASE'
  #     env_name: ${{ inputs.restore_environment }}
  #   secrets:
  #     gh_token: ${{ secrets.GH_TOKEN }}
  #     encryption_key: ${{ secrets.GH_ENCRYPTION_PASSWORD }}

  sync-env:
    # needs:
    #   - get-backup-user
    #   - get-backup-host
    #   - get-backup-encryption-key
    #   - get-backup-ssh-key
    name: Sync GitHub env to Kubernetes
    environment: ${{ inputs.environment }}
    runs-on:
      - self-hosted
      - k8s
      - ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v6
      # Create a temporary file for environment variables
      # to store GitHub Secrets and Variables (base64 encoded)
      # Making those values base64 encoded allows us to avoid further complex escaping issues
      # with special characters and multiline values when generating Kubernetes Secret manifests
      - name: Export all secrets and environment variables
        run: |
            ENV_FILE=$(mktemp)
            jq -n -r '
                [${{ toJSON(secrets) }}, ${{ toJSON(vars) }}] 
                | add
                | with_entries(.value |= @base64)
                | to_entries[] 
                | "\(.key)=\(.value)"
            ' > $ENV_FILE

            echo env_file=$ENV_FILE >> $GITHUB_ENV
            cat $ENV_FILE
      # - name: Save secrets
      #   if: needs.get-backup-user.outputs.environment_exists == 'true'
      #   run: |
      #     echo "${{ needs.get-backup-user.outputs.secret_value }}" | base64 --decode | \
      #     openssl enc -aes-256-cbc -pbkdf2 -d -salt -k "${{ secrets.GH_ENCRYPTION_PASSWORD }}" -out /tmp/backup_user
      #     echo "${{ needs.get-backup-host.outputs.secret_value }}" | base64 --decode | \
      #     openssl enc -aes-256-cbc -pbkdf2 -d -salt -k "${{ secrets.GH_ENCRYPTION_PASSWORD }}" -out /tmp/backup_host
      #     echo "${{ needs.get-backup-encryption-key.outputs.secret_value }}" | base64 --decode | \
      #     openssl enc -aes-256-cbc -pbkdf2 -d -salt -k "${{ secrets.GH_ENCRYPTION_PASSWORD }}" -out /tmp/backup_encryption_key
      #     echo "${{ needs.get-backup-ssh-key.outputs.secret_value }}" | base64 --decode | \
      #     openssl enc -aes-256-cbc -pbkdf2 -d -salt -k "${{ secrets.GH_ENCRYPTION_PASSWORD }}" -out /tmp/backup_ssh_key
      #     echo BACKUP_USER=$(cat /tmp/backup_user | base64) >> $env_file
      #     echo BACKUP_HOST=$(cat /tmp/backup_host | base64) >> $env_file
      #     echo BACKUP_ENCRYPTION_PASSPHRASE=$(cat /tmp/backup_encryption_key | base64) >> $env_file
      #     echo BACKUP_HOST_PRIVATE_KEY=$(cat /tmp/backup_ssh_key | base64) >> $env_file

      - name: Preprocess mapping into Secret YAMLs
        run: |
          set -euo pipefail
          mkdir -p k8s-secrets

          mapping_file=".github/TEMPLATES/secret-mapping-${{ inputs.namespace_template }}.yml"

          # Iterate over all kubernetes secret names in mapping
          for secret_name in $(yq e 'keys | .[]' "$mapping_file"); do
          skip_manifest=false
          type=$(yq e ".\"$secret_name\".\"type\"" "$mapping_file")
          if [ -z "$type" ] || [ "$type" == "null" ]; then
            type="Opaque"
          fi
          namespace=$(yq e ".\"$secret_name\".\"namespace\"" "$mapping_file")
          if [ -z "$namespace" ] || [ "$namespace" = "null" ]; then
            namespace="${{ inputs.namespace_template }}-${{ inputs.environment }}"
          fi
          echo "🔧 Generating Secret: $secret_name, type: $type"
          {
            echo "data:"
            while IFS= read -r key; do
              # Skip comments
              if echo "$key" | grep -q "^[[:space:]]*#"; then
                continue
              fi

              if echo "$key" | grep -q ":"; then
                github_var=$(echo "$key" | cut -d: -f1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
                k8s_var=$(echo "$key" | cut -d: -f2 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
              else
                github_var="$key"
                k8s_var="$key"
              fi

              value=$(grep "^$github_var=" "$env_file" | cut -d= -f2- || true)

              if [ -n "$value" ]; then
                echo "  $k8s_var: $value"
              else
                echo "⚠️  Warning: $github_var not found in env_file → setting $k8s_var as empty" >&2
                echo "  $k8s_var: ''"
                skip_manifest=true
              fi
            done < <(yq e ".\"$secret_name\".\"data\"[]" "$mapping_file")
            echo "apiVersion: v1"
            echo "kind: Secret"
            echo "type: $type"
            echo "metadata:"
            echo "  name: $secret_name"
            echo "  namespace: $namespace"
          } > "k8s-secrets/$secret_name.yaml"
          if [ "$skip_manifest" == "true" ]; then
            echo "⚠️  Skipping Kubernetes secret $secret_name due to empty or not defined GitHub secrets or variables"
            rm -f "k8s-secrets/$secret_name.yaml"
          fi
          done

      - name: Map Dockerhub credentials if available
        env:
          # TODO: Rename to DOCKERHUB_USERNAME after swarm migration
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME || '' }}
          # TODO: Rename to DOCKERHUB_TOKEN after swarm migration 
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN || '' }}
          DOCKERHUB_SECRET_NAME: ${{ vars.DOCKERHUB_SECRET_NAME || 'dockerhub-credentials' }}
          NAMESPACE_TEMPLATE: ${{ inputs.namespace_template }}
        run: |
          if [ -n "$DOCKERHUB_USERNAME" ] && [ -n "$DOCKERHUB_TOKEN" ] && [ "z$NAMESPACE_TEMPLATE" = "zopencrvs" ]; then
            kubectl create secret docker-registry "$DOCKERHUB_SECRET_NAME" \
              --docker-server=https://index.docker.io/v1/ \
              --docker-username="$DOCKERHUB_USERNAME" \
              --docker-password="$DOCKERHUB_TOKEN" \
              --namespace="${NAMESPACE_TEMPLATE}-${{ inputs.environment }}" \
              --dry-run=client -o yaml > "k8s-secrets/$DOCKERHUB_SECRET_NAME.yaml"
            echo "✅ Generated Docker Registry Secret manifest: k8s-secrets/$DOCKERHUB_SECRET_NAME.yaml"
          else
            echo "ℹ️  Dockerhub credentials not provided, skipping Docker Registry Secret creation for $DOCKERHUB_SECRET_NAME"
          fi

      - name: Apply secrets to Kubernetes
        run: |
          echo "✅ Generated manifests:"
          ls -l k8s-secrets
          set -euo pipefail
          for f in k8s-secrets/*.yaml; do
            namespace=$(yq e ".metadata.namespace" "$f")
            [ "$namespace" == "null" ] && echo "ℹ️  No namespace defined for $f, skipping secret creation" && continue
            echo "🚀 Applying $f within namespace"
            kubectl get namespace $namespace >/dev/null 2>&1 || kubectl create namespace $namespace
            yq eval . "$f" > /dev/null && echo "✅ $f is valid YAML" || echo "❌ $f has YAML errors" && cat "$f"
            kubectl apply -n $namespace -f "$f"
            echo "Dropping last-applied-configuration annotation for secret $(basename ${f/.yaml/})"
            kubectl annotate secret -n $namespace "$(basename ${f/.yaml/})" kubectl.kubernetes.io/last-applied-configuration-
          done

      - name: Cleanup secrets and variables
        if: always()
        run: |
          rm -fv $env_file
          rm -fvr k8s-secrets
