name: Info job
on:
  workflow_call: {}
  workflow_dispatch: {}
jobs:
  self-test:
    runs-on: [self-hosted]
    steps:
        - name: Cleanup environment
          run: |
            ls -l /var/run/secrets/kubernetes.io/serviceaccount
            env
            echo "Environment: $ENV"
            which kubectl            
            kubectl get pods -A
