name: Reindex data
run-name: "Reindex data on ${{ inputs.environment }} environment"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - demo
          - dev
          - dev-stg
  workflow_call:
    inputs:
      environment:
        type: string
jobs:
  reindex:
    environment: ${{ inputs.environment }}
    env:
      namespace: opencrvs-${{ inputs.environment }}
    runs-on:
      - self-hosted
      - k8s
      - ${{ inputs.environment }}
    steps:
      - name: Get helm release values and Quote specific fields that are commonly numeric
        run: |
          helm get values opencrvs -n ${namespace} -ojson | \
            jq '
              if has("image") and (.image | has("tag")) and (.image.tag | type == "number") then
                .image.tag = (.image.tag | tostring)
              else . end |
              if has("version") and (.version | type == "number") then
                .version = (.version | tostring)
              else . end |
              if has("service") and (.service | has("port")) and (.service.port | type == "number") then
                .service.port = (.service.port | tostring)
              else . end
            ' > ${namespace}.json
      - name: Reindex data
        run: |
          kubectl delete job -n ${namespace} elasticsearch-reindex || true
          helm template -f ${namespace}.json \
              --namespace ${namespace} \
              -s templates/elasticsearch-reindex.yaml \
              oci://ghcr.io/opencrvs/opencrvs-services | kubectl apply -n ${namespace} -f -
          sleep 30;
          kubectl logs job/elasticsearch-reindex -f -n ${namespace} || true
          kubectl wait --for=condition=complete job/elasticsearch-reindex -n ${namespace} --timeout=600s;
