name: Seed data
run-name: "Seed data to ${{ inputs.environment }} environment"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - demo-prod
  workflow_call:
    inputs:
      environment:
        type: string
jobs:
  seed:
    environment: ${{ inputs.environment }}
    env:
      namespace: opencrvs-${{ inputs.environment }}
    runs-on:
      - self-hosted
      - k8s
      - ${{ inputs.environment }}
    steps:
      - name: Get helm release values and Quote specific fields that are commonly numeric
        run: |
          helm get values opencrvs -n ${namespace} -ojson | \
            jq '
              if has("image") and (.image | has("tag")) and (.image.tag | type == "number") then
                .image.tag = (.image.tag | tostring)
              else . end |
              if has("version") and (.version | type == "number") then
                .version = (.version | tostring)
              else . end |
              if has("service") and (.service | has("port")) and (.service.port | type == "number") then
                .service.port = (.service.port | tostring)
              else . end
            ' > ${namespace}.json
      - name: Seeding data
        run: |
          kubectl delete job --wait -n ${namespace} data-seed || true
          helm template -f ${namespace}.json \
              --set data_seed.enabled=true \
              --namespace ${namespace} \
              -s templates/data-seed-job.yaml \
              oci://ghcr.io/opencrvs/opencrvs-services | kubectl apply -n ${namespace} --wait --timeout=600s -f -
          kubectl get pods -n ${namespace} -lapp=data-seed
          kubectl wait --for=condition=Complete job/data-seed -n ${namespace} --timeout=600s; RES=$?
          kubectl logs job/data-seed -f -n ${namespace}
          exit $RES
