name: Seed data (k8s)
run-name: Seed data to ${{ inputs.environment }} core=${{ inputs.core-image-tag }}
on:
    workflow_dispatch:
      inputs:
        core-image-tag:
          description: "Core image tag"
          required: true
          default: "develop"
          type: string        
        environment:
          description: "Target environment"
          required: true
          default: "demo"
          type: string
    workflow_call:
      inputs:
        environment:
          required: true
          type: string
        core-image-tag:
          required: true
          type: string
jobs:
  seed:
    env:
      ENV: ${{ inputs.environment }}
      CORE_IMAGE_TAG: ${{ inputs.core-image-tag }}
    runs-on: [self-hosted]
    steps:
        # FYI: Checkout is needed only due to single file: k8s-env/opencrvs/values.yaml
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Get values from deployed release
          run: helm get values opencrvs --namespace opencrvs-${ENV} > values-${ENV}.yaml
        - name: Seeding data
          run: |
            kubectl delete job -n opencrvs-${ENV} data-seed || true
            kubectl delete pod -n opencrvs-${ENV} -lapp=events;
            sleep 30;
            kubectl wait --for=condition=ready pod -n opencrvs-${ENV} -lapp=events;
            helm template -f values-${ENV}.yaml \
                --set data_seed.enabled=true \
                --namespace opencrvs-${ENV} \
                -s templates/data-seed-job.yaml \
                oci://ghcr.io/opencrvs/opencrvs-services | kubectl apply -n opencrvs-${ENV} -f -
            sleep 30;
            kubectl logs job/data-seed -f -n opencrvs-${ENV} || true
            kubectl wait --for=condition=complete job/data-seed -n opencrvs-${ENV} --timeout=600s;
            kubectl delete pod -n opencrvs-${ENV} -lapp=events;
