name: Seed data
run-name: "Seed data to ${{ inputs.environment }} environment"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
  workflow_call:
    inputs:
      environment:
        type: string
jobs:
  seed:
    environment: ${{ inputs.environment }}
    env:
      namespace: opencrvs-${{ inputs.environment }}
    runs-on:
      - self-hosted
      - k8s
      - ${{ inputs.environment }}
    steps:
      - name: Get helm release values and Quote specific fields that are commonly numeric
        run: |
          helm get values opencrvs -n ${namespace} -ojson | \
            jq '
              if has("image") and (.image | has("tag")) and (.image.tag | type == "number") then
                .image.tag = (.image.tag | tostring)
              else . end |
              if has("version") and (.version | type == "number") then
                .version = (.version | tostring)
              else . end |
              if has("service") and (.service | has("port")) and (.service.port | type == "number") then
                .service.port = (.service.port | tostring)
              else . end
            ' > ${namespace}.json
      - name: Seeding data
        run: |
          kubectl delete job -n opencrvs-${ENV} data-seed || true
          kubectl delete pod -n opencrvs-${ENV} -lapp=events;
          sleep 30;
          kubectl wait --for=condition=ready pod -n opencrvs-${ENV} -lapp=events;
          helm template -f ${namespace}.json \
              --set data_seed.enabled=true \
              --namespace opencrvs-${ENV} \
              -s templates/data-seed-job.yaml \
              oci://ghcr.io/opencrvs/opencrvs-services | kubectl apply -n opencrvs-${ENV} -f -
          sleep 30;
          kubectl logs job/data-seed -f -n opencrvs-${ENV} || true
          kubectl wait --for=condition=complete job/data-seed -n opencrvs-${ENV} --timeout=600s;
          kubectl delete pod -n opencrvs-${ENV} -lapp=events;
