name: Release Charts

on:
  push:
    branches:
      - develop

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package helm charts
        run: |
          mkdir packages
          charts=$(ls -1 charts)
          for chart in $(ls -1 charts)
          do
            helm package charts/$chart --destination packages
          done
      - name: Publish helm charts
        env:
            GITHUB_TOKEN_REGISTRY: ${{ secrets.PACKAGE_GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN_REGISTRY | helm registry login ghcr.io/opencrvs --username adskyiproger --password-stdin
          for package in $(ls -1 packages)
          do
            helm push packages/$package oci://ghcr.io/opencrvs
          done
