name: Release Charts

on:
  push:
    branches:
      - develop

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package helm charts
        run: |
          mkdir packages
          charts=$(ls -1 charts)
          for chart in $(ls -1 charts)
          do
            helm package charts/$chart --destination packages
          done
