name: Reset environment on Kubernetes
run-name: "Reset environment (core: ${{ inputs.core-image-tag }})"
on:
    workflow_dispatch:
      inputs:
        core-image-tag:
          description: "Core image tag"
          required: true
          default: "develop"
          type: string        
        environment:
          description: "Target environment"
          required: true
          default: "demo"
          type: choice
          options:
            - dev
            - demo
jobs:
  reset:
    env:
      ENV: ${{ inputs.environment }}
      CORE_IMAGE_TAG: ${{ inputs.core-image-tag }}
    runs-on: [self-hosted]
    steps:
        # FYI: Repository is needed only due to single file: infrastructure/dev/dependenciess/values.yaml
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Cleanup environment
          run: |
            kubectl delete job -n opencrvs-${ENV} data-cleanup || true
            helm template -f examples/${ENV}/opencrvs-services/values.yaml \
                --set data_cleanup.enabled=true \
                --set image.tag="$CORE_IMAGE_TAG" \
                --namespace opencrvs-${ENV} \
                -s templates/data-cleanup-job.yaml \
                oci://ghcr.io/opencrvs/opencrvs-services | kubectl apply -n opencrvs-${ENV} -f -
            sleep 30;
            kubectl logs job/data-cleanup -f --all-containers=true -n opencrvs-${ENV} || true
            kubectl wait --for=condition=complete job/data-cleanup -n opencrvs-${ENV} --timeout=600s;
            kubectl delete pod -n opencrvs-${ENV} -lapp=events;
            kubectl wait --for=condition=ready pod -n opencrvs-${ENV} -lapp=events;
        - name: Migration
          run: |
            kubectl delete job -n opencrvs-${ENV} data-migration || true
            helm template -f examples/${ENV}/opencrvs-services/values.yaml \
                -s templates/data-migration-job.yaml \
                --set image.tag="$CORE_IMAGE_TAG" \
                --namespace opencrvs-${ENV} \
                oci://ghcr.io/opencrvs/opencrvs-services | kubectl apply -n opencrvs-${ENV} -f -
            sleep 30;
            kubectl logs job/data-migration -f -n opencrvs-${ENV} || true
            kubectl wait --for=condition=complete job/data-migration -n opencrvs-${ENV} --timeout=600s;
        - name: Seeding data
          run: |
            kubectl delete job -n opencrvs-${ENV} data-seed || true
            kubectl delete pod -n opencrvs-${ENV} -lapp=events;
            kubectl wait --for=condition=ready pod -n opencrvs-${ENV} -lapp=events;
            helm template  -f examples/${ENV}/opencrvs-services/values.yaml \
                --set data_seed.enabled=true \
                --set image.tag="$CORE_IMAGE_TAG" \
                --namespace opencrvs-${ENV} \
                -s templates/data-seed-job.yaml \
                oci://ghcr.io/opencrvs/opencrvs-services | kubectl apply -n opencrvs-${ENV} -f -
            sleep 30;
            kubectl logs job/data-seed -f -n opencrvs-${ENV} || true
            kubectl wait --for=condition=complete job/data-seed -n opencrvs-${ENV} --timeout=600s;
            kubectl delete pod -n opencrvs-${ENV} -lapp=events;
