name: Update workflow environments

on:
  workflow_dispatch:
  push:
    branches: ["*"]
    paths:
      - infrastructure/server-setup/inventory/*
      - .github/workflows/update-envs.yml

jobs:
  update-environments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
            token: ${{ secrets.GH_TOKEN }}

      - name: Extract available infrastructure names
        id: extract_infrastructure
        run: |
          INFRA_ENVIRONMENTS=(`find infrastructure/server-setup/inventory -type f -name "*.yml" -exec basename {} .yml \;`)
          echo "env_list=${INFRA_ENVIRONMENTS[@]}" >> "$GITHUB_OUTPUT"
          echo "List of existing infrastructure configurations:"
          echo "${INFRA_ENVIRONMENTS[@]}"
      - name: Extract available environment names
        id: extract_environment
        run: |
          ENVIRONMENTS=(`find  environments/ -type d -maxdepth 1 -exec basename {} \;`)
          echo "env_list=${ENVIRONMENTS[@]}" >> "$GITHUB_OUTPUT"
          echo "List of existing environment configurations:"
          echo "${ENVIRONMENTS[@]}"
      - name: Update workflows with new infrastructure configurations
        run: |
          workflows=(
            ".github/workflows/provision.yml"
          )
          path=".on.workflow_dispatch.inputs.environment.options"

          IFS=' ' read -r -a envs <<< "${{ steps.extract_infrastructure.outputs.env_list }}"
          list=$(printf '"%s", ' "${envs[@]}")
          list="[${list%, }]"
          for wf in "${workflows[@]}"; do
            echo "Updating $wf with: ${list}"
            yq e "$path = $list" "$wf" -i
          done
      - name: Update workflows with new environment configurations
        run: |
          workflows=(
            ".github/workflows/deploy-dependencies.yml"
            ".github/workflows/deploy-opencrvs.yml"
            ".github/workflows/k8s-reset-data.yml"
            ".github/workflows/k8s-seed-data.yml"
          )
          path=".on.workflow_dispatch.inputs.environment.options"

          IFS=' ' read -r -a envs <<< "${{ steps.extract_environment.outputs.env_list }}"
          list=$(printf '"%s", ' "${envs[@]}")
          list="[${list%, }]"
          for wf in "${workflows[@]}"; do
            echo "Updating $wf with: ${list}"
            yq e "$path = $list" "$wf" -i
          done
      - name: Show diff
        run: git diff
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .github/workflows/*.yml
          git commit -m "Update environment options" || echo "No changes"
          git push
