#cloud-config
packages:
  - curl
users:
  - name: cluster
    ssh-authorized-keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINgMcsSBwTE0EbMDRSF1T4vJDcN/5HAjKGbi2DqV7g/Q vmudryi@opencrvs.org"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
runcmd:
  - "apt-get update -y"
  - |
    curl https://get.k3s.io | sh -
    chown cluster:cluster /etc/rancher/k3s/k3s.yaml
    chown cluster:cluster /var/lib/rancher/k3s/server/node-token
#     kubectl taint nodes ${node_name} node.cloudprovider.kubernetes.io/uninitialized:NoSchedule-
