#cloud-config
packages:
  - curl
users:
  - name: provision
    ssh-authorized-keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC7urAt3KYs4Io/53yS87QQj3qJ5/AL+seqG1J+VrF13 vmudryi@NB01NSTL012"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
