#cloud-config
packages:
  - curl
users:
  - name: cluster
    ssh-authorized-keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINgMcsSBwTE0EbMDRSF1T4vJDcN/5HAjKGbi2DqV7g/Q vmudryi@opencrvs.org"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
