# TODO:
# Before running any deployment don't forget to create kubernetes secret minio-secret
# Example:
# Create file minio.env with content:
# MINIO_ACCESS_KEY=minioadmin
# MINIO_SECRET_KEY=minioadmin
# MINIO_BUCKET=ocrvs
# MINIO_ROOT_USER=minioadmin
# MINIO_ROOT_PASSWORD=minioadmin
#
# Run command:
# kubectl create secret generic minio-secret --from-env-file=minio.env --namespace <opencrvs-namespace>

resources:
  memoryRequest: "512Mi"
  cpuRequest: "500m"
  memoryLimit: "1Gi"
  cpuLimit: "2"

hostname: k8s.opencrvs.dev

image:
  tag: develop
  # tag: 50b3e14
# redis_host: my-keydb.opencrvs-deps-dev.svc.cluster.local

countryconfig:
  image:
    # Replace countryconfig with farajaland to test data
    name: opencrvs/ocrvs-farajaland
    # name: opencrvs/ocrvs-countryconfig
    tag: develop
    # Farajaland working tag: ec53c12
    # tag: ec53c12

documents:
# Uncomment this section to add authentication for MinIO:
  secrets:
    minio-secret:
      - MINIO_ACCESS_KEY
      - MINIO_BUCKET
      - MINIO_SECRET_KEY

gateway:
  secrets:
  # Uncomment this section to add authentication for MinIO:
    minio-secret:
    # TODO: Check if it is needed
    - MINIO_BUCKET

migration:
  secrets:
# Uncomment this section to add authentication for MinIO:
    minio-secret:
      - MINIO_ACCESS_KEY
      - MINIO_BUCKET
      - MINIO_SECRET_KEY

data_seeder:
  # Change to true to enable data seeder
  enabled: true