resources:
  memoryRequest: "512Mi"
  cpuRequest: "300m"
  memoryLimit: "1Gi"
  cpuLimit: "2"

hostname: k8s.opencrvs.dev

image:
  tag: develop

countryconfig:
  image:
    # Replace countryconfig with farajaland to test data
    name: opencrvs/ocrvs-farajaland
    # name: opencrvs/ocrvs-countryconfig
    tag: develop

documents:
  secrets:
    minio-secret:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY

# gateway:
  # secrets:
  # # Uncomment this section to add authentication for MinIO:
  #   minio-secret:
  #   # TODO: Check if it is needed
  #   - MINIO_BUCKET

migration:
  secrets:
# Uncomment this section to add authentication for MinIO:
    minio-secret:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY

data_seeder:
  # Change to true to enable data seeder
  enabled: true