# FIXME: Once real values are populated drop `tmp` suffix
dashboards-admin-user:
  # Email address for metabase admin panel login
  - OPENCRVS_METABASE_ADMIN_EMAIL
  # Password for metabase admin panel login
  - OPENCRVS_METABASE_ADMIN_PASSWORD

elasticsearch-admin-user:
  # The Elasticsearch superuser password.
  - ELASTICSEARCH_SUPERUSER_PASSWORD: ELASTIC_PASSWORD

minio-opencrvs-users:
  - MINIO_ROOT_USER:MINIO_ACCESS_KEY
  - MINIO_ROOT_PASSWORD:MINIO_SECRET_KEY
  # Next secrets are needed for data cleanup job:
  # A username for a Minio superuser admin to login to the Minio console to view supporting document attachments submitted during registrations. https://minio-console.<your_domain>
  - MINIO_ROOT_USER
  # A password for a Minio superuser admin
  - MINIO_ROOT_PASSWORD

mongodb-admin-user:
  # The MongoDB superuser admin username. A powerful account that has all rights to OpenCRVS data
  - MONGODB_ADMIN_USER
  # The MongoDB superuser admin password.
  - MONGODB_ADMIN_PASSWORD

postgres-admin-user:
  - POSTGRES_USER
  - POSTGRES_PASSWORD

smtp-config:
  - SENDER_EMAIL_ADDRESS
  - SMTP_HOST
  - SMTP_PASSWORD
  - SMTP_PORT
  - SMTP_SECURE
  - SMTP_USERNAME
  - ALERT_EMAIL

# TODO:
# ACTIVATE_USERS
# NOTIFICATION_TRANSPORT
# A prop which can be used to configure either Email or SMS for staff and beneficiary comms or potentially both.
