dashboards-admin-user-tmp:
  # Email address for metabase admin panel login
  - OPENCRVS_METABASE_ADMIN_EMAIL
  # Password for metabase admin panel login
  - OPENCRVS_METABASE_ADMIN_PASSWORD

elasticsearch-admin-user-tmp:
  # The Elasticsearch superuser password.
  - ELASTICSEARCH_SUPERUSER_PASSWORD: ELASTIC_PASSWORD
