# BACKUP_ENCRYPTION_PASSPHRASE

# This is the password that is used to encrypt all the backups that OpenCRVS creates from a production server and that are stored on the backup server. Use this passphrase to decrypt the backups.

elasticsearch-admin-user:
  # The Elasticsearch superuser password. You can also use this to login to Kibana with the username "elastic" and you have superuser Elastic privileges. Kibana URL: https://kibana.<your_domain>
  - ELASTICSEARCH_SUPERUSER_PASSWORD: ELASTIC_PASSWORD

# KIBANA_USERNAME

# A username for a regular Kibana user to login and monitor OpenCRVS stack health. Useful for developers as this user will have no superuser privileges.

# KIBANA_PASSWORD

# A password for a regular Kibana user to login and monitor OpenCRVS stack health

# MONGODB_ADMIN_USER

# The MongoDB superuser admin username. A powerful account that has all rights to OpenCRVS data

# MONGODB_ADMIN_PASSWORD

# The MongoDB superuser admin password.

minio-opencrvs-users:
  # A username for a Minio superuser admin to login to the Minio console to view supporting document attachments submitted during registrations. https://minio-console.<your_domain>
  - MINIO_ROOT_USER
  # A password for a Minio superuser admin
  - MINIO_ROOT_PASSWORD

# SMTP_HOST

# SMTP_PORT

# SMTP_USERNAME

# SMTP_PASSWORD

# SMTP_SECURE

# Whether or not your SMTP port requires TLS

# ALERT_EMAIL

# Email address or Slack channel address to send system technical alerts to.

# SENDER_EMAIL_ADDRESS


# REPLICAS

# The number of replicas: 1, 2, 3 or 5 depending on how many servers are in the environment cluster

# DOMAIN

# The host domain name (without www!) for your environment.

# CONTENT_SECURITY_POLICY_WILDCARD

# This string is supplied to the clients and nginx config and ensures that the format of your domain above can be configurable for CORS purposes.

# ACTIVATE_USERS


# NOTIFICATION_TRANSPORT

# A prop which can be used to configure either Email or SMS for staff and beneficiary comms or potentially both.
