# FIXME: Once real values are populated drop `tmp` suffix
dashboards-admin-user-tmp:
  # Email address for metabase admin panel login
  - OPENCRVS_METABASE_ADMIN_EMAIL
  # Password for metabase admin panel login
  - OPENCRVS_METABASE_ADMIN_PASSWORD

elasticsearch-admin-user-tmp:
  # The Elasticsearch superuser password.
  - ELASTICSEARCH_SUPERUSER_PASSWORD: ELASTIC_PASSWORD

minio-opencrvs-users-tmp:
  # A username for a Minio superuser admin to login to the Minio console to view supporting document attachments submitted during registrations. https://minio-console.<your_domain>
  - MINIO_ROOT_USER:MINIO_ACCESS_KEY
  # A password for a Minio superuser admin
  - MINIO_ROOT_PASSWORD:MINIO_SECRET_KEY


# DOMAIN

# The host domain name (without www!) for your environment.

# CONTENT_SECURITY_POLICY_WILDCARD

# This string is supplied to the clients and nginx config and ensures that the format of your domain above can be configurable for CORS purposes.

# ACTIVATE_USERS

# NOTIFICATION_TRANSPORT

# A prop which can be used to configure either Email or SMS for staff and beneficiary comms or potentially both.
